### ISSUE TITLE
Unable to attach to process by using gdb.attach

### ISSUE THREAD

**Issue by krnbhargav** [pwndbg/pwndbg#1000]
Please can somebody help me , i newly install ubuntu ,came from arch ,in arch i donot have this error

![image](https://user-images.githubusercontent.com/44202642/149460448-d98fbca6-f129-4d3a-bd71-cc3b483420e3.png)
when attaching to process using `gdb.attach()` for breakpoint setting i am getting this error
![image](https://user-images.githubusercontent.com/44202642/149460506-f18830a9-0bb4-4f2c-a608-b9d4a1d28863.png)

i also try to fix using [this](https://askubuntu.com/questions/41629/after-upgrade-gdb-wont-attach-to-process), but getting pwndbg core modules error 
so is there any way i can fix this

**Comment by disconnect3d** [comment]
It seems your issue is just a misconfiguration and not a bug in Pwndbg or Pwntools (from which the `gdb.attach` API comes from) and it worked in Arch due to having different configuration than Ubuntu.

In your screenshot you can actually see what is the problem:
> Could not attach to process. (...) check the settings of /proc/sys/kernel/yama/ptrace_scope, or try again as the root user (...)

While the "try again as the root user" should just work, I would rather recommend against it as it is dangerous to do so.

Linux has a [Yama LSM (Linux Security Module)](https://www.kernel.org/doc/Documentation/security/Yama.txt) which control whether a given user can use the [`ptrace` syscall](https://man7.org/linux/man-pages/man2/ptrace.2.html) to attach to (debug) another process. This is a security measure taken to prevent Linux malware from attaching to other processes and compromising them (e.g. stealing their secrets & other sensitive data).

This Yama LSM can be configured with Linux's runtime configuration that is available either via the `sysctl` command or the `/proc/sys/` directory of the [`proc(5)` filesystem](https://wiki.archlinux.org/title/Procfs).

If you look into the [documentation](https://www.kernel.org/doc/Documentation/security/Yama.txt), it can have one of the following values:
```
The sysctl settings (writable only with CAP_SYS_PTRACE) are:

0 - classic ptrace permissions: a process can PTRACE_ATTACH to any other
    process running under the same uid, as long as it is dumpable (i.e.
    did not transition uids, start privileged, or have called
    prctl(PR_SET_DUMPABLE...) already). Similarly, PTRACE_TRACEME is
    unchanged.

1 - restricted ptrace: a process must have a predefined relationship
    with the inferior it wants to call PTRACE_ATTACH on. By default,
    this relationship is that of only its descendants when the above
    classic criteria is also met. To change the relationship, an
    inferior can call prctl(PR_SET_PTRACER, debugger, ...) to declare
    an allowed debugger PID to call PTRACE_ATTACH on the inferior.
    Using PTRACE_TRACEME is unchanged.

2 - admin-only attach: only processes with CAP_SYS_PTRACE may use ptrace
    with PTRACE_ATTACH, or through children calling PTRACE_TRACEME.

3 - no attach: no processes may use ptrace with PTRACE_ATTACH nor via
    PTRACE_TRACEME. Once set, this sysctl value cannot be changed.
```

You can read your system's current value of this setting with either the `sysctl kernel.yama.ptrace_scope` command or by reading the corresponding procfs file via the `cat /proc/sys/kernel/yama/ptrace_scope` command (as it just renders this value).

 Now, I guess that in your case this value is most likely "1". This would mean that one can call `ptrace(PTRACE_ATTACH, ...)` (a syscall to attach to and debug another process) only if this process is a children of the current process. This means that doing `gdb ./binary` and then starting debugging from GDB (e.g. via `starti` command) should just work.

However, in your case when you use pwntools and its `gdb.attach(...)` API the debugger that is started is not a parent of the process you want to debug, so - if your `yama/ptrace_scope` is configured to "1" - the Yama LSM blocks this syscall so that it fails.

You can solve this by changing this configuration to "0" in which a process can attach to other processes that are running under the same uid (were spawned by the same user). Okay, there is also the condition of process being dumpable, but that's something that is likely irrelevant/not changed here.

So how you can reconfigure the Yama's `ptrace_scope` setting? Either via `sysctl`:
```
sysctl -w kernel.yama.ptrace_scope=0
```
Or by writing to the corresponding procfs file:
```
echo 0 > /proc/sys/kernel/yama/ptrace_scope
```

This will require root privileges and will reconfigure the Yama LSM as described above. Please note that this is a global setting so it influences the whole system and may lower its security a little bit. Given this, you should probably set it back to "1" after you finish what you need it reconfigured for.

**Comment by krnbhargav** [comment]
i donot know why it is not fixing @disconnect3d,
![image](https://user-images.githubusercontent.com/44202642/150076309-136266db-8a2e-492e-b889-b3de4cefcad0.png)
![image](https://user-images.githubusercontent.com/44202642/150076336-bd189886-d030-434a-962f-eded4f52b4fb.png)

**Comment by krnbhargav** [comment]
when using root i am getting this ->
![image](https://user-images.githubusercontent.com/44202642/150081639-06e92281-c3cc-4c04-8c35-d36590331739.png)
