### ISSUE TITLE
vmmap with qemu-user doesn't seem to work

### ISSUE THREAD

**Issue by jasonyu1996** [pwndbg/pwndbg#1013]
### Description

Hi! Despite the claims in the feature list, I was unable to make vmmap work with qemu-user (qemu-x86_64). All that it shows is this
```
pwndbg> vmmap
LEGEND: STACK | HEAP | CODE | DATA | RWX | RODATA
               0x0 0xffffffffffffffff rwxp ffffffffffffffff 0      [qemu]
```

My understanding is that for a qemu target, such information is obtained from auxv, so probably the output of auxv would be helpful:
```
AT_PHDR                  0x4000000040 ◂— 0x400000006
AT_PHENT                 0x38
AT_PHNUM                 0xb
AT_PAGESZ                0x1000
AT_BASE                  0x4001806000 ◂— jg     0x4001806047 /* 0x10102464c457f */
AT_FLAGS                 0x0
AT_ENTRY                 0x4000001050 ◂— xor    ebp, ebp /* 0x89485ed18949ed31 */
AT_UID                   0x3e8
AT_EUID                  0x3e8
AT_GID                   0x3e8
AT_EGID                  0x3e8
AT_HWCAP                 0x78bfbfd
AT_CLKTCK                0x64
AT_RANDOM                0x40018050d0 ◂— jnp    0x40018050df /* 0x74e9a0b07c240d7b */
AT_SECURE                0x0
AT_EXECFN                ./prog
AT_PLATFORM              i686
```

### Steps to reproduce

* `qemu-x86_64 -g 1234 ./prog`
* Inside qemu: `target remote localhost:1234`
* Inside qemu: `vmmap`

### My setup

GDB:
```
pwndbg> version
Gdb:      10.1.90.20210103-git
Python:   3.9.2 (default, Feb 28 2021, 17:03:44)  [GCC 10.2.1 20210110]
Pwndbg:   1.1.0 build: e9b9ebe
Capstone: 4.0.1024
Unicorn:  1.0.2
```

Python
```
3.9.2 (default, Feb 28 2021, 17:03:44)
[GCC 10.2.1 20210110]
```

**Comment by disconnect3d** [comment]
Hey,

> My understanding is that for a qemu target, such information is obtained from auxv, so probably the output of auxv would be helpful:

Not really, or, not full vmmap information can be obtained this way.

The main problem here is that the QEMU user emulation gdbstub does not provide the information **it could expose to GDB**. For example, QEMU itself has a code that handles the debugged program's syscall and if it reads /proc/self/maps QEMU will read its own maps and remove the ones that belong to QEMU leaving the debugged program's maps. And this is what we could do here too: we could read QEMU's process maps and filter them - this is what GEF does iirc. However, the problem with this is that it will not work when QEMU is run on a remote server.

Ofc this can still be worked around by e.g. finding memory page boundaries by trying to derefence values that are stored in registers but such solution is still far from perfect.

I started extending QEMU recently so that it could provide the `info proc mappings` information to GDB. This work can be tracked here: https://www.mail-archive.com/qemu-devel@nongnu.org/msg872546.html and I would recommend getting this patch locally and recompiling QEMU to get all this working, heh.

I still need to add some tests to this before it gets merged, but hopefully it won't take that much time.

**Comment by gsingh93** [comment]
Dup of https://github.com/pwndbg/pwndbg/issues/981
