### ISSUE TITLE
Adding pwntools cyclic or some kind of pattern create for pwndbg

### ISSUE THREAD

**Issue by neverm0r** [pwndbg/pwndbg#1068]
I have been using pwndbg for a while and kind of enjoyed some shell command that is invoked into pwndbg shell. So I want to readd some  shell commands that I feel really useful like pwntools command line :)

**Comment by disconnect3d** [comment]
Sorry for the troubles. This has been removed in https://github.com/pwndbg/pwndbg/pull/1064 and while indeed one can use those shell commands with just `!<command>` I think we shouldn't make this such drastically.

Here are some options we can do:
1. Revert that PR
2. Revert the PR and deprecate those commands - inform the users that they can just do `!<command>` instead of executing them directly and that they will be removed
3. Bring back only the interesting commands. This is tough, but I believe the only interesting ones are those comming from pwntools. We can pull `pwntools` as dependency and create those commands directly with better interface. This way, e.g. the `asm` command will by default use current architecture instead of requiring one to pass it.

I think we will go with the 3rd option :)

**Comment by disconnect3d** [comment]
@Galahan-1 I reverted the commit for now and applied the https://github.com/pwndbg/pwndbg/commit/51bc5e22453ed5466c9b5bbd492c01f63e4937ce changes.

I think we will proceed with more or less 3rd solution of moving pwntools commands directly into pwndbg code in the soonish future instead of calling them from shell. I will add a separate issue for that matter.
