### ISSUE TITLE
Clear screen before printing context

### ISSUE THREAD

**Issue by j3s5e4** [pwndbg/pwndbg#1165]
### Discussed in https://github.com/pwndbg/pwndbg/discussions/1164

As discussed (see below), can the screen be cleared before the next instruction or printing context so that each element of the output stays in a consistent location?

<div type='discussions-op-text'>

<sup>Originally posted by **JesseAusten** September 25, 2022</sup>
I've noticed pwndbg doesn't refresh the screen each time I step an instruction like gef does, as in the register context isn't lined up with the top of the screen, it just keeps whatever fits. Is there a way to clear the screen each time I step through a program?</div>

**Comment by stnevans** [comment]
`set context-clear-screen on` should do this.

**Comment by j3s5e4** [comment]
That worked, thank you! Should that be something that's on by default rather than adding it to an init script?

**Comment by stnevans** [comment]
I personally like having the history over alignment. Not sure how others feel.

**Comment by j3s5e4** [comment]
Oh that doesn't actually keep the history so there's no way to scroll up and see output or previous commands?

**Comment by disconnect3d** [comment]
I also like having history so I am not sure if we should change the default. We can add a https://github.com/pwndbg/pwndbg/blob/dev/pwndbg/lib/tips.py about it.

**Comment by gsingh93** [comment]
I use `tmux`, so it keeps the history for me. But it would good if it kept the history regardless. `gef`s implmentation probably does this since they're just using control characters, we can probably do something similar.

**Comment by j3s5e4** [comment]
It seems that `gdb> shell clear -x` keeps history while clearing the screen, similar to `^L` in the shell. It seems that's also what gef uses.

**Comment by disconnect3d** [comment]
Oh, that's nice. Maybe we could have: `set context-clear-mode` with three values?:
1. One that would clear the screen but keep the history
2. Second that would clear the screen but not keep history (our current `set context-clear-screen on`)
3. Third that would not clear the screen and not keep history (out current default)

Wdyt? Not sure how to name those values though :)

Or just... use 1) and do not support 2) or 3)?

**Comment by gsingh93** [comment]
I don't think 2 is necessary, not sure that anyone would prefer that over 1. I think keeping the current default, option 3, around (but not enabled by default) would still be good to have.

**Comment by disconnect3d** [comment]
> Oh that doesn't actually keep the history so there's no way to scroll up and see output or previous commands?

Wait, I just checked locally and I can scroll up myshell to get the previous output after setting `set context-clear-screen on` in Pwndbg.

We are currently using this for clearing the screen:
```py
def clear_screen(out=sys.stdout):
    """
    Clear the screen by moving the cursor to top-left corner and
    clear the content
    """
    out.write("\x1b[H\x1b[J")
```

And this is also what GEF may fallback to if there is a `tty` included. Why may it clear history for you?

**Comment by disconnect3d** [comment]
Okay, that is interesting. The behavior depends on the used terminal; here, on Ubuntu 22.04 with `set context-clear-screen on` I get this behavior:
* gnome-terminal - does not save history
* gnome-terminal + screen session - does save history
* terminator - does save history

**Comment by disconnect3d** [comment]
Also, I'd prefer to not rely on the `clear` binary if possible.

Interesting: https://askubuntu.com/a/997893

So we are doing:
```py
out.write("\x1b[H\x1b[J")
```
And that askubuntu thread suggests doing:
```
out.write("\x1b[H\x1b[2J")
```

And... that seems to work for me - it does not remove the scrollback buffer when clearing the screen.

**Comment by disconnect3d** [comment]
Here is the explanation for that weird escape sequence codes: https://en.wikipedia.org/wiki/ANSI_escape_code#CSIsection. Also thx to @gwynbleidd @vesim987 and other who helped me out to figure some of this stuff.

So what we use is:
* `\x1b`  -  Escape | Starts all the escape sequences
* `[`  -  Control Sequence Introducer | Starts most of the useful sequences, terminated by a byte in range 0x40-0x7E
* `H` -  Cursor Position | Moves the cursor to row n, column m. The values are 1-based, and default to 1 (top left corner) if omitted. A sequence such as CSI ;5H is a synonym for CSI 1;5H as well as CSI 17;H is the same as CSI 17H and CSI 17;1H
* `\x1b`  -  Escape | Starts all the escape sequences
* `<n> J` -  Erase in Display | Clears part of the screen. If n is 0 (or missing), clear from cursor to end of screen. If n is 1, clear from cursor to beginning of the screen. If n is 2, clear entire screen (and moves cursor to upper left on DOS ANSI.SYS). If n is 3, clear entire screen and delete all lines saved in the scrollback buffer (this feature was added for xterm and is supported by other terminal applications

Now, remember that when we execute "Erase in Display" we are already in row=col=1 set by the `H` escape sequence. 

Currently, we have J without a `<n>` so it is 0: we clear from cursor to end of screen and it works on some terminals (`terminator` or `gnome-terminal + screen`) but does not on others.

When we change `<n>` to 2, which is "clear entire screen", the scrollback seems to work on **more terminals**.

So what's the difference between the terminals? It turns out there is this [`terminfo` thing on Linux](https://man7.org/linux/man-pages/man5/terminfo.5.html) that defines escape codes for given actions for given terminals. And we can query this info for current terminal with `infocmp` program. E.g. here we can see the `clear` command for different terminals:

terminator:
```
user@user:~$ echo $TERM
xterm-256color
user@user:~$ infocmp | grep clear
	clear=\E[H\E[2J, cnorm=\E[?12l\E[?25h, cr=\r,
```

gnome-terminal:
```
user@user:~$ echo $TERM
xterm-256color
user@user:~$ infocmp | grep clear
	clear=\E[H\E[2J, cnorm=\E[?12l\E[?25h, cr=\r,
user@user:~$ 
```

tmux in terminator:
```
user@user:~$ echo $TERM
screen
user@user:~$ infocmp | grep clear
        clear=\E[H\E[J, cnorm=\E[34h\E[?25h, cr=\r,
```

AFAIU in order to support all possible terminals, we would have to parse terminfo for current terminal and figure out the proper command to do what we want. And I bet it may still not work properly for something non standard.

Let's just change the used escape sequence to use the '2' variant and see how it goes from now on.

**Comment by disconnect3d** [comment]
@JesseAusten Can you test `set context-clear-screen on` after https://github.com/pwndbg/pwndbg/commit/3b2f7796d663d1c9562265a86aa81105069129f7 ? It should now properly preserve scrollback history on most terminals.

**Comment by j3s5e4** [comment]
It works perfectly now using `set context-clear-screen on`, thanks. I'm using the default gnome-terminal on Ubuntu 22.04.
