### ISSUE TITLE
`entry` command doesn't work with gdbserver

### ISSUE THREAD

**Issue by gsingh93** [pwndbg/pwndbg#1255]
The `entry` command sets a breakpoint at the entrypoint of a program, which is different than the first instruction (`starti` can be used for that). The problem is that after setting `break_on_first_instruction = True` (which will set the entry breakpoint in a StartEvent handler), we start the binary with `run`.

`gdbserver` doesn't support `run`, but it does support `starti`, so the `entry` command doesn't work here. To fix this, we should probably use `starti` followed by `continue` instead of `run`, at least if we detect we're using `gdbserver`.

**Comment by disconnect3d** [comment]
> gdbserver doesn't support run, but it does support starti

Are you sure?

```
pwndbg> starti
The "remote" target does not support "run".  Try "help target" or "continue".
```

With this, not sure if we can do anything more here other than improving the displayed error ( ? ).

**Comment by gsingh93** [comment]
> With this, not sure if we can do anything more here other than improving the displayed error ( ? ).

I think we just run `continue` instead of `run`? I was mistaken that `gdbserver` supports `starti`, I only assumed that because it always starts on the first instruction when I launch it from `pwntools`.

**Comment by disconnect3d** [comment]
Hmm, why would we run `continue` instead of `run` if `entry` effectively restarts the process? If the current gdbserver connection doesn't allow for that (I think there is a mode to achieve that) `entry` should probably just do nothing?

I guess the motivation for such change could be scripting GDB with Pwntools and its remote debugging vs local debugging maybe? But then having different behavior depending on the mode could be confusing?

**Comment by gsingh93** [comment]
The context for this issue has been completely evicted from my cache. I'm sure it'll come up again, when it does I'll reopen this and add more details.
