### ISSUE TITLE
Add some commands for selectively turn specific sub-context off/on

### ISSUE THREAD

**Issue by Squirre17** [pwndbg/pwndbg#1479]
**Describe the solution you'd like**
e.g. If stack-context not desirable for me in some cases, and it occupy a mass of terminal space, I need to turn it off.
`ctx stack off` cmd better that current `set context-sections regs disasm code ghidra backtrace expression` (which don't set the stack in config)

Sketchy idea is that add a global variable dict (str -> bool) for filter and memorize all on/off.
Or ugly but simply `gdb.execute("set context-sections...")` in context funtion every time when encounter a off/on cmd.(Seems maybe not need extra modification beyond context function).

**Comment by gsingh93** [comment]
Another idea, we could add these two commands (or one `ctx-section` command with two subcommands):
- `ctx-add-section <section> [<index>]`: Appends `<section>` to context-sections by default, otherwise inserts it at the specified `<index>` in the list of sections, allowing you to more easily control the position
- `ctx-remove-section <section>`: Removes `<section>` from `context-sections`

But your suggestion of simply having a variable that tracks whether a section should be shown or not could also work, in which case we'd leave the `context-sections` list untouched. I'm not sure right now which one would be a better solution.

**Comment by Squirre17** [comment]
> Another idea, we could add these two commands (or one `ctx-section` command with two subcommands):
> 
> * `ctx-add-section <section> [<index>]`: Appends `<section>` to context-sections by default, otherwise inserts it at the specified `<index>` in the list of sections, allowing you to more easily control the position
> * `ctx-remove-section <section>`: Removes `<section>` from `context-sections`
> 
> But your suggestion of simply having a variable that tracks whether a section should be shown or not could also work, in which case we'd leave the `context-sections` list untouched. I'm not sure right now which one would be a better solution.

I think the **one ctx-section command with two subcommands** is better one. `ctx-section add stack` or `ctx-section rm stack` have less word.
If I want re-add it after removing a section, in this scenario ,former solution I only need delete last two word in console (by two ctrl-W). But `ctx-add-section <section> [<index>]` or `ctx-remove-section <section>` I need to remove it all and re-typing all word. Cuz almost section add/remove operation have high correlation to one specific context. Maybe `ctx-section stack add/rm` can more less word modification :P. This order is trivial but can take into consideration if it's easy to implementation.

**Comment by disconnect3d** [comment]
Hm... we already have: `ctx regs` or `ctx stack` and even `regs` (we also have `stack` but it works the same way as `telescope` but targeting the stack pointer).

So adding `ctx <section[s]> [on|off]` may be a nice improvement here?

On the other hand... setting parameters through commands may not be that great since `set <...>` should be used for that. But having separate commands is more convenient so I guess it may make sense to have it in the long run?

We could also have `set context-sections -` to switch back to the last setting (and saving the current as last) similarly to what `cd -` does in shell. (I think that `set context-sections -` now does set it to null).

**Comment by diivi** [comment]
Which format did we finally decide to go ahead with for this command/subcommand?

**Comment by gsingh93** [comment]
I'm fine with @disconnect3d's suggestion of `ctx <section[s]> [on|off]`, essentially adding this feature to the existing command.

**Comment by disconnect3d** [comment]
@Squirre17 this was implemented in #2442 :)
