### ISSUE TITLE
Failing installation 

### ISSUE THREAD

**Issue by tony-josi** [pwndbg/pwndbg#1512]
### Description

Failing installation for while following the "Installation is straightforward:" section of the root folder readme with following error:

```
  Using cached cffi-1.15.1-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (442 kB)
Installing collected packages: unicorn, sortedcontainers, pyserial, pyelftools, urllib3, typing-extensions, tabulate, six, pysocks, Pygments, pycparser, psutil, plumbum, pip, packaging, MarkupSafe, intervaltree, idna, charset-normalizer, certifi, capstone, bcrypt, rpyc, ROPGadget, requests, python-dateutil, pathlib2, mako, colored-traceback, cffi, pynacl, cryptography, paramiko, pwntools
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
launchpadlib 1.10.13 requires testresources, which is not installed.
Successfully installed MarkupSafe-2.1.1 Pygments-2.13.0 ROPGadget-7.2 bcrypt-4.0.1 capstone-4.0.2 certifi-2022.12.7 cffi-1.15.1 charset-normalizer-2.1.1 colored-traceback-0.3.0 cryptography-39.0.0 idna-3.4 intervaltree-3.1.0 mako-1.2.4 packaging-23.0 paramiko-2.12.0 pathlib2-2.3.7.post1 pip-22.3.1 plumbum-1.8.1 psutil-5.9.4 pwntools-4.8.0 pycparser-2.21 pyelftools-0.29 pynacl-1.5.0 pyserial-3.5 pysocks-1.7.1 python-dateutil-2.8.2 requests-2.28.1 rpyc-5.3.0 six-1.16.0 sortedcontainers-2.4.0 tabulate-0.8.10 typing-extensions-4.3.0 unicorn-2.0.1.post1 urllib3-1.26.13
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
+ grep pwndbg /home/ubuntu/.gdbinit
```

### Steps to reproduce
```
git clone https://github.com/pwndbg/pwndbg
cd pwndbg
./setup.sh
```

### My setup

OS
```
NAME="Ubuntu"
VERSION="20.04.5 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.5 LTS"
VERSION_ID="20.04"
```
GDB

`GNU gdb (Ubuntu 9.2-0ubuntu1~20.04.1) 9.2`

Python

`Python 3.8.10`

Commit

`commit 85e55130d30159b15e265193bddbe536ba37bdaa (HEAD -> dev, origin/dev, origin/HEAD)`

**Comment by disconnect3d** [comment]
Hi,

Interesting, the:
> ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
> launchpadlib 1.10.13 requires testresources, which is not installed.

does not seem like a problem with Pwndbg dependencies but with system dependencies. On the other hand, we are installing our deps to the system's Python installation so maybe some other problem that your dependencies have appears.

Can you try to do `sudo apt install python3-testresources` and see if it works and fixes your problem?

**Comment by tony-josi** [comment]
Thanks, it worked.

Can it be checked/added in the setup.sh

**Comment by disconnect3d** [comment]
It could be, but I am still thinking about the best solution here.

Ideally, you would want all the dependencies to be installed in a [Python virtual environment](https://docs.python.org/3/tutorial/venv.html) but iirc there were some potential problems with using such for GDB+Pwndbg. This is because GDB is linked to a specific Python version at build time and if you spawn a virtualenv with a different Python versions, you may get ABI incompatibility with e.g. Python modules written as C extensions.

But we do support virtualenvs in Pwndbg and [warn the users that it may not work (though its rare)](https://github.com/pwndbg/pwndbg/blob/85e55130d30159b15e265193bddbe536ba37bdaa/gdbinit.py#L16-L71).

Some possible solutions to this:
1) We could grep for this specific error and tell the user to install `python3-testresources` -- we probably shouldn't install it on our own since it is not really our dependency but a result of incorrect/invalid user's environment
2) Add an option to install Pwndbg deps in a virtualenv created by us -- we could use the GDB's Python to create the virtual environment, but then where should we store the actual venv? I thought it could maybe be problematic for pkg managers that install things in read-only mode like Nix but [Pwndbg in nixpkgs do not use our install.sh at all](https://github.com/NixOS/nixpkgs/blob/1fbb6f1a584bdd0f339373340d01e84f25c68cbb/pkgs/development/tools/misc/pwndbg/default.nix)
3) Perhaps we could install Pwndbg in a virtualenv by default?

**Comment by disconnect3d** [comment]
@gsingh93 do u think we should change setup.sh to install in a venv and enable that venv from gdbinit.py? 🤐

**Comment by gsingh93** [comment]
I think if we could make it optional to start, i.e. `./setup.sh --venv`, that would be great. I think this is what you suggest in option 2 above, but I'm not sure I understand the problem with it.

**Comment by gsingh93** [comment]
Closing this, the issue to track installing in a venv is here: https://github.com/pwndbg/pwndbg/issues/1634
