### ISSUE TITLE
`slab info` is broken on latest version of Linux kernel

### ISSUE THREAD

**Issue by gsingh93** [pwndbg/pwndbg#1523]
At some point between kernel versions 5.10 and 6.1.5 the names of some of the struct fields changed, fix should be straightforward.

**Comment by clark-ja** [comment]
I also just stumbled upon this today and for completeness here are my findings:

In kernel version 5.17 a separate `struct slab` from `struct page` was [introduced](https://elixir.bootlin.com/linux/v5.17/source/mm/slab.h#L9).

Furthermore, in the `struct kmem_cache_cpu`, the `page` and `partial` members of type `struct page *` where replaced by the `slab` and `partial` members of type `struct slab *`.

As far as I can see, for kernel versions `>= 5.17` the following [line](https://github.com/pwndbg/pwndbg/blob/dev/pwndbg/commands/slab.py#L168) for `pwndbg/commands/slab.py` needs to be adjusted:

```py
page = cpu_cache["page"] # should be `page = cpu_cache["slab"]` depending on kernel version
```
and then also in `print_cpu_cache()` the `slab['pages']` needs to be replaced with `slab['slabs']`.

Not sure how `pwndbg` wants to do kernel version checks in its codebase though. I did find `pwndbg.gdblib.kernel.kversion()`, but it returns a `str` and is therefore not best suited for the task unless further processed...

EDIT:

Actually, there are already changes in kernel version 5.16 which should be addressed in pwndbg: there the `struct page`s member `pobjects` was removed (and pwndbgs `print_cpu_cache()` method uses it)

Instead of `pobjects` in linux kernel `== 5.16` (`mm/slub.c`) the value is calculated in-line [as follows](https://elixir.bootlin.com/linux/v5.16/source/mm/slub.c#L5484):
```c
/* Approximate half-full pages, see slub_set_cpu_partial() */
objects = (pages * oo_objects(s->oo)) / 2;
```
and then updated to [this](https://elixir.bootlin.com/linux/v5.17/source/mm/slub.c#L5489) in linux kernel versions `>= 5.17`:
```c
/* Approximate half-full slabs, see slub_set_cpu_partial() */
objects = (slabs * oo_objects(s->oo)) / 2;
```

**Comment by gsingh93** [comment]
Thanks @theguy147! I don't have time to make these changes at the moment, would you be able to make a PR?

We'd still like to support any LTS kernel, so instead of removing the original code, we should add some sort of version check. If there are debug symbols we can use this: https://github.com/pwndbg/pwndbg/blob/d7f459c169e390095dd1ef98e3eacd328a0b6fc5/pwndbg/gdblib/kernel/__init__.py#L74

If there aren't, maybe we can fallback to a config that the user can set?

**Comment by clark-ja** [comment]
I also do not have that much time at my hand but i did take a look and apart from the changes in kernel versions 5.16/5.17 there appear to be some inconsistencies in the `slab` command that need to be fixed as well, e.g., different possible memory models (FLATMEM vs SPARSEMEM vs SPARSEMEM_VMEMMAP) and even some bugs such as the variable `__START_KERNEL_map` vs `__START_KERNEL_MAP` vs `START_KERNEL_map` and other issues.

I started to work on it but I can't promise a timely PR if I don't figure all of those things out and manage to test a good chunk of it for a bunch of kernel versions and configurations... (Probably all manual testing as I don't think testing different kernels will be easily possible in the CI pipeline)

**Comment by gsingh93** [comment]
> I started to work on it but I can't promise a timely PR if I don't figure all of those things out and manage to test a good chunk of it for a bunch of kernel versions and configurations...

I don't think it's necessary to solve all the issues at once 😄 We can improve this iteratively, fixing support for one kernel version or configuration at a time.

The kernel images used for testing are generated from https://github.com/gsingh93/linux-exploit-dev-env. It shouldn't be too difficult to add more versions, but I think we should focus on making sure everything works on the LTS kernels and master first before testing on non-LTS kernels.

**Comment by clark-ja** [comment]
I finally got around to at least make the most relevant changes (I think). But the PR isn't ready yet as I haven't had the time to look at how pwndbg does testing (in general and also specifically for the linux kernel). But I opened a Draft PR so others can play around with it...

**Comment by gsingh93** [comment]
Should be fixed now, thanks for your work on this.
