### ISSUE TITLE
Using setup.sh for dependency updates

### ISSUE THREAD

**Issue by Cnly** [pwndbg/pwndbg#1657]
**Is your feature request related to a problem? Please describe.**

#1620 broke a few things for me:

* I run setup.sh every time I pull changes from this repo to check for dependency updates, at which point I'd obviously have the source line in my ~/.gdbinit. And the new version of the script won't leave it untouched.
* The above is actually run in my non-interactive script, but now that script would stop at the prompt.

**Describe the solution you'd like**

Perhaps we can skip checking/touching ~/.gdbinit if a `DONT_UPDATE_GDBINIT` env var is set? I could do a PR for this.

**Describe alternatives you've considered**

Alternatively, maybe we can extract the dependency installation part from setup.sh to a new update.sh? But this can also be implemented indirectly with the above solution.

**Additional context**

(I moved my comment https://github.com/pwndbg/pwndbg/pull/1620#issuecomment-1480749018 to this independent thread.)

**Comment by disconnect3d** [comment]
Or instead of an envvar, we could have `./install.sh --update` flag? I think that would be a nice solution to have.

Btw we also want to support `./install.sh --venv` to install all Python deps in a virtual environment, but then I think we would have to detect if Pwndbg venv is present somewhere (also: where to put it?) and use it if its available (add it to `sys.path` I guess?).

**Comment by Cnly** [comment]
`./install.sh --update` sounds better indeed! How about I do a PR for this?

As for `--venv`, I'm not sure, but there seems to be another issue #1634 for this. Is there some designated directory by gdb or pwndbg for plugins, etc.? If not, how about `~/.cache`?
