### ISSUE TITLE
Error when install it in latest kali

### ISSUE THREAD

**Issue by siwind** [pwndbg/pwndbg#1690]
When i run setup.sh,  i got the following message:

```
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
pyppeteer 1.0.1 requires pyee<9.0.0,>=8.1.0, but you have pyee 9.0.4 which is incompatible.
crackmapexec 5.4.0 requires aioconsole<0.4.0,>=0.3.3, but you have aioconsole 0.3.1 which is incompatible.
crackmapexec 5.4.0 requires minikerberos==0.3.3, but you have minikerberos 0.4.0 which is incompatible.
crackmapexec 5.4.0 requires neo4j<5.0.0,>=4.1.1, but you have neo4j 5.2.dev0 which is incompatible.
crackmapexec 5.4.0 requires paramiko<3.0.0,>=2.7.2, but you have paramiko 3.1.0 which is incompatible.
crackmapexec 5.4.0 requires pypsrp<0.8.0,>=0.7.0, but you have pypsrp 0.8.1 which is incompatible.
crackmapexec 5.4.0 requires xmltodict<0.13.0,>=0.12.0, but you have xmltodict 0.13.0 which is incompatible.
ospd-openvas 22.4.6 requires packaging<21.0,>=20.4, but you have packaging 23.1 which is incompatible.
rich 13.3.1 requires pygments<3.0.0,>=2.14.0, but you have pygments 2.13.0 which is incompatible.
python-gvm 23.2.0 requires paramiko<3.0.0,>=2.7.1, but you have paramiko 3.1.0 which is incompatible.
Successfully installed MarkupSafe-2.1.2 Pygments-2.13.0 ROPGadget-7.2 bcrypt-4.0.1 capstone-4.0.2 certifi-2022.12.7 cffi-1.15.1 charset-normalizer-3.1.0 colored-traceback-0.3.0 cryptography-40.0.2 idna-3.4 intervaltree-3.1.0 mako-1.2.4 packaging-23.1 paramiko-3.1.0 pip-23.1.2 plumbum-1.8.1 psutil-5.9.4 pwntools-4.9.0 pycparser-2.21 pyelftools-0.29 pynacl-1.5.0 pyserial-3.5 pysocks-1.7.1 python-dateutil-2.8.2 requests-2.29.0 rpyc-5.3.1 six-1.16.0 sortedcontainers-2.4.0 tabulate-0.8.10 types-requests-2.29.0.0 types-urllib3-1.26.25.11 typing-extensions-4.3.0 unicorn-2.0.1.post1 urllib3-1.26.15
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
```

And my kali  OS in vmware workstation is:
```
$ uname -a
Linux Kali 6.1.0-kali7-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.1.20-2kali1 (2023-04-18) x86_64 GNU/Linux
```

**Comment by disconnect3d** [comment]
Hey,

Our installer installs packages to the system's Python which is generally not great, but worked so far.

Your Kali seems to have lots of python packages installed into the system's Python and some of their versions conflict with Pwndbg's requirements.

You can one of those solutions:
1. Install Python dependencies in a Python virtual environment and then use that venv when you run GDB. Ofc don't forget putting `source $pwndbg-path/gdbinit.py` into the `~/.gdbinit` file that is loaded by GDB on startup (which is required to initialize Pwndbg when GDB starts). This is the best solution which should work. We will move to virtualenv in our installer in the future (https://github.com/pwndbg/pwndbg/issues/1634).
2. Try to remove the version requirements in `requirements.txt` file and re-run `./setup.sh`. This may however break some stuff in Pwndbg if the version u have is older and we require new one etc.
3. Use a docker container (which you may want to run with `--cap-add=SYS_PTRACE` or `--cap-add=PTRACE`). We have a `docker-compose.yml` file that defines container images for our CI, but which can be easily reused locally e.g. with `docker-compose run ubuntu22.04 bash` (you may want to do it differently though).

I am going to close this issue since it will be fixed when #1634 is merged and we really need to do that because installing packages to system python is just bad.
