### ISSUE TITLE
heap or bins command is not working on android device

### ISSUE THREAD

**Issue by yzcmf** [pwndbg/pwndbg#1897]
No matter using gef, pwndbg or pwngdb or peda; While runing those commands in android phone with gdbserver, never get the heap command work ? Is there anything with libc.so ? Should I install libc.so debug version in android ? I don't know how to install the debug version of libc.so in android phone ?  
Anyone know how to solve this problem

gef➤  heap arenas
gef➤  heapinfo
Can not get libc version
Cannot get main_arena's symbol address. Make sure you install libc debug file (libc6-dbg & libc6-dbg:i386 for debian package).
Can't find heap info
gef➤  heapbase
Python Exception <class 'FileNotFoundError'>: [Errno 2] No such file or directory: '/proc/12607/maps'
Python Exception <class 'gdb.error'>: Error occurred in Python: [Errno 2] No such file or directory: '/proc/12607/maps'
Error occurred in Python: Error occurred in Python: [Errno 2] No such file or directory: '/proc/12607/maps'
gef➤  parseheap
Can not get libc version
Cannot get main_arena's symbol address. Make sure you install libc debug file (libc6-dbg & libc6-dbg:i386 for debian package).
can't find heap info
gef➤  heap
[!] Syntax
heap (chunk|chunks|bins|arenas|set-arena)
gef➤  heap chunks
[!] Invalid arena
gef➤

**Comment by CptGibbon** [comment]
I don't think Android has used the default GLIBC memory allocator for some time now

**Comment by disconnect3d** [comment]
Yes. Android uses [Bionic](https://en.wikipedia.org/wiki/Bionic_(software)), their own implementation of the C standard library. Our heap commands support only glibc for now.

I would be happy if anyone would want to implement support for any other standard library but I guess this won't happen that soon.

Closing this since we can't do much with it now (it's not really a bug).
