### ISSUE TITLE
UnicodeEncodeError, Python Exception occured

### ISSUE THREAD

**Issue by dhje0ng** [pwndbg/pwndbg#2104]
```
pwndbg> version
Gdb:      12.1
Python:   3.10.12 (main, Nov 20 2023, 15:14:05) [GCC 11.4.0]
Pwndbg:   2024.02.14 build: e7548c7f
Capstone: 5.0.1280
Unicorn:  2.0.1
pwndbg>
```

I am using Ubuntu 22.04 AMD64 distribution on AWS cloud and after installing pwndbg, I am getting some errors.
When you run gdb, PWNDBG runs, but you get an error statement like the one below.

```
******
Your encoding (ANSI_X3.4-1968) is different than UTF-8. pwndbg might not work properly.
You might try launching GDB with:
    LC_CTYPE=C.UTF-8 gdb
If that does not work, make sure that en_US.UTF-8 is uncommented in /etc/locale.gen and that you called `locale-gen` command
******
pwndbg: loaded 156 pwndbg commands and 48 shell commands. Type pwndbg [--shell | --all] [filter] for a list.
pwndbg: created $rebase, $base, $ida GDB functions (can be used with print/break)
Traceback (most recent call last):
  File "/home/ubuntu/pwndbg/gdbinit.py", line 74, in <module>
    import pwndbg  # noqa: F401
  File "/home/ubuntu/pwndbg/pwndbg/__init__.py", line 88, in <module>
    config_mod.init_params()
  File "/home/ubuntu/pwndbg/pwndbg/gdblib/config.py", line 122, in init_params
    Parameter(p)
  File "/home/ubuntu/pwndbg/pwndbg/gdblib/config.py", line 43, in __init__
    self.value = param.value
UnicodeEncodeError: 'ascii' codec can't encode characters in position 0-1: ordinal not in range(128)
```

To resolve the UNICODE issue, we have identified the following actions in a previously discussed issue report.

```

echo "LC_CTYPE: $LC_CTYPE"

LC_CTYPE: UTF-8

echo "LC_ALL: $LC_ALL"

LC_ALL: en_US.UTF-8

```
I also ran the `locale-gen` command.

However, none of the above errors are resolved.

The command that works to resolve a UnicodeEncodeError is 

`LC_CTYPE=C.UTF-8 gdb` But this is very cumbersome for me, so I need a better way. 

Incidentally, I tried downloading and installing pwndbg.git again, but that didn't solve the problem.

```
Python Exception <class 'AttributeError'>: partially initialised module 'pwndbg' has no attribute 'lib' (most likely due to a circular import)

```

What is causing this error?

There is nothing in my pwndbg directory with the same filename (*.py).

**Comment by disconnect3d** [comment]
Well, there are two issues here.

First is encoding. It is described in the error log you provided:
```
Your encoding (ANSI_X3.4-1968) is different than UTF-8. pwndbg might not work properly.
You might try launching GDB with:
    LC_CTYPE=C.UTF-8 gdb
If that does not work, make sure that en_US.UTF-8 is uncommented in /etc/locale.gen and that you called `locale-gen` command
```

You need to generate and set an UTF-8 locale in your system. If you don't do it properly, GDB will fail to use some unicode characters and sadly, currently, throw an error that you saw.

An alternative is to set the locale as shown, you can do it for your shell environment by writing `export LC_CTYPE=C.UTF-8` into the script that runs on your shell initialization like `~/.bashrc` (if using bash) or `~/.zshrc` (if using zsh). However, this may influence some other programs you would run in the terminal, so it may not be the best option long term. (Also, you need to re-run your shell after writing to the *rc file, so the script gets re-run and sets the environment variable).

The second problem you have is:

> Incidentally, I tried downloading and installing pwndbg.git again, but that didn't solve the problem.
> `Python Exception <class 'AttributeError'>: partially initialised module 'pwndbg' has no attribute 'lib' (most likely due to a circular import)`

It seems to me, that you either have something broken in `~/.gdbinit`, the script that runs on GDB launch, which we write to during Pwndbg installation so that Pwndbg script is loaded on GDB startup, or, maybe you have installed both a Pwndbg release package and cloned the repo and ran the `setup.sh` script. In that case, you should run one or another, not both.

**Comment by dhje0ng** [comment]
@disconnect3d Thank you for your response. I have changed the language settings on my system to There are potentially other issues, but I don't think it will be a big deal in this environment since the purpose is to use pwndbg.



I will close this issue as the issue has been resolved.
