### ISSUE TITLE
black formatter still used in devcontainer.json after switch to ruff

### ISSUE THREAD

**Issue by CptGibbon** [pwndbg/pwndbg#2145]
Folks using editors that honor devcontainer.json still have their PR code formatted by black on save, which was recently replaced by ruff as the project formatter.

**Comment by CptGibbon** [comment]
@gsingh93 before I make this change, there's a little more going on with regards to linting & formatting.

For example:
*  pyproject.toml tells ruff to limit line length to 100 characters, then tells it to ignore line length during linting
* There are some leftover black directives in pyproject.toml
* ruff can also do import sorting, but isort is still used in lint.sh

**Comment by gsingh93** [comment]
- I think currently line length is mainly for the formatter, and ignored by the linter. I think the reason for the ignore is that there are some lines it's too annoying to split and we didn't want the lint warnings.
- let's remove everything related to black
- ruff can do import sorting, but it's a little weird because it's part of the linter and not the formatter. Shouldn't be a problem, but just needed to look into it more before making the change

**Comment by CptGibbon** [comment]
@gsingh93 do you know which linter made the changes you committed in https://github.com/pwndbg/pwndbg/pull/2082/commits/063e1472a55fff7963fc6c3c15c0cc07676cdc0a?
This isn't how isort does it...

**Comment by gsingh93** [comment]
It's isort, but it's because of this config option: https://github.com/pwndbg/pwndbg/blob/dev/pyproject.toml#L123

**Comment by CptGibbon** [comment]
> It's isort, but it's because of this config option: https://github.com/pwndbg/pwndbg/blob/dev/pyproject.toml#L123

Oh I see, perhaps I should add isort to the devcontainer.json actions too.
