### ISSUE TITLE
Context exceptions with ARM target

### ISSUE THREAD

**Issue by mat-pr** [pwndbg/pwndbg#2153]
### Description

Vaguely similar to #1097.
When debugging an ARM target with qemu-system-arm, the `context` command fails to execute with the following backtraces:

```
'context': Print out the current register, instruction, and stack context.
Traceback (most recent call last):
  File "/home/m/Desktop/pwndbg/pwndbg/commands/__init__.py", line 197, in __call__
    return self.function(*args, **kwargs)
  File "/home/m/Desktop/pwndbg/pwndbg/commands/__init__.py", line 357, in _OnlyWhenRunning
    return function(*a, **kw)
  File "/home/m/Desktop/pwndbg/pwndbg/commands/context.py", line 406, in context
    func(
  File "/home/m/Desktop/pwndbg/pwndbg/commands/context.py", line 514, in context_regs
    regs = get_regs()
  File "/home/m/Desktop/pwndbg/pwndbg/commands/context.py", line 606, in get_regs
    desc = pwndbg.chain.format(value)
  File "/home/m/Desktop/pwndbg/pwndbg/chain.py", line 174, in format
    enhanced = pwndbg.enhance.enhance(
  File "/home/m/Desktop/pwndbg/pwndbg/enhance.py", line 119, in enhance
    pwndbg_instr = pwndbg.disasm.one(value, enhance=False)
  File "/home/m/Desktop/pwndbg/pwndbg/disasm/__init__.py", line 244, in one
    for insn in get(address, 1, emu, enhance=enhance, from_cache=from_cache, put_cache=put_cache):
  File "/home/m/Desktop/pwndbg/pwndbg/disasm/__init__.py", line 278, in get
    i = get_one_instruction(
  File "/home/m/Desktop/pwndbg/pwndbg/disasm/__init__.py", line 211, in get_one_instruction
    md = get_disassembler(address)
  File "/home/m/Desktop/pwndbg/pwndbg/disasm/__init__.py", line 161, in get_disassembler
    extra = CS_MODE_THUMB if (pwndbg.gdblib.regs.cpsr & (1 << 5)) else CS_MODE_ARM
TypeError: unsupported operand type(s) for &: 'NoneType' and 'int'
```

and

```
'context': Print out the current register, instruction, and stack context.
Traceback (most recent call last):
  File "/home/m/Desktop/pwndbg/pwndbg/commands/__init__.py", line 197, in __call__
    return self.function(*args, **kwargs)
  File "/home/m/Desktop/pwndbg/pwndbg/commands/__init__.py", line 357, in _OnlyWhenRunning
    return function(*a, **kw)
  File "/home/m/Desktop/pwndbg/pwndbg/commands/context.py", line 406, in context
    func(
  File "/home/m/Desktop/pwndbg/pwndbg/commands/context.py", line 635, in context_disasm
    result = pwndbg.gdblib.nearpc.nearpc(
  File "/home/m/Desktop/pwndbg/pwndbg/gdblib/nearpc.py", line 129, in nearpc
    instructions, index_of_pc = pwndbg.disasm.near(
  File "/home/m/Desktop/pwndbg/pwndbg/disasm/__init__.py", line 349, in near
    emu = pwndbg.emu.emulator.Emulator()
  File "/home/m/Desktop/pwndbg/pwndbg/emu/emulator.py", line 194, in __init__
    self.uc_mode = self.get_uc_mode()
  File "/home/m/Desktop/pwndbg/pwndbg/emu/emulator.py", line 544, in get_uc_mode
    mode |= U.UC_MODE_THUMB if (pwndbg.gdblib.regs.cpsr & (1 << 5)) else U.UC_MODE_ARM
TypeError: unsupported operand type(s) for &: 'NoneType' and 'int'
```

Patching the two reported lines in `pwndbg/pwndbg/disasm/__init__.py` and `pwndbg/pwndbg/emu/emulator.py`, the debugging process seems reasonable.

### Steps to reproduce

I ran `gdb-multiarch` on the ARM binary. Then the first exception is triggered with
```
set exception-verbose on
target remote localhost:1234
```
and the second with an additional `next` command.

### My setup

```
Platform: Linux-6.5.0-28-generic-x86_64-with-glibc2.35
OS: Ubuntu 22.04.4 LTS
OS ABI: #29~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Thu Apr  4 14:39:20 UTC 2
Architecture: x86_64
Endian: little
Charset: utf-8
Width: 101
Height: 57
Gdb:      12.1
Python:   3.10.12 (main, Nov 20 2023, 15:14:05) [GCC 11.4.0]
Pwndbg:   2024.02.14 build: 00adfbbb
Capstone: 5.0.1280
Unicorn:  2.0.1
This GDB was configured as follows:
   configure --host=x86_64-linux-gnu --target=x86_64-linux-gnu
	     --with-auto-load-dir=$debugdir:$datadir/auto-load
	     --with-auto-load-safe-path=$debugdir:$datadir/auto-load
	     --with-expat
	     --with-gdb-datadir=/usr/share/gdb (relocatable)
	     --with-jit-reader-dir=/usr/lib/gdb (relocatable)
	     --without-libunwind-ia64
	     --with-lzma
	     --with-babeltrace
	     --with-intel-pt
	     --with-mpfr
	     --with-xxhash
	     --with-python=/usr (relocatable)
	     --with-python-libdir=/usr/lib (relocatable)
	     --with-debuginfod
	     --without-guile
	     --enable-source-highlight
	     --with-separate-debug-dir=/usr/lib/debug (relocatable)
	     --with-system-gdbinit=/etc/gdb/gdbinit
	     --with-system-gdbinit-dir=/etc/gdb/gdbinit.d

("Relocatable" means the directory can be moved with the GDB installation
tree, and GDB will still find it.)
```
pwndbg commit: 00adfbbb5e06564f7d351624e09dae898f485c57

**Comment by gsingh93** [comment]
cc: @OBarronCS since this is in the emulation code you'll be refactoring.

**Comment by OBarronCS** [comment]
Based on the error, it looks likes the `CPSR` register is not present in the specific Arm architecture in use (resulting in `pwndbg.gdblib.regs.cpsr` returning `None`). I know that the `Cortex-M` processors don't have the CPSR register, however Pwndbg has some detection for the `armcm` architecture which avoids these code paths that access `.cpsr`. 

The bug may be that our detection of Cortex-M is missing some cases. Would it be possible for you (@mat-pr) to share the output of `show architecture` and `pi gdb.newest_frame().architecture().name()` in GDB while debugging? Would you know how the binary was compiled? The output of `info reg` would be very helpful as well (it will print a bunch of stuff, but the very first 30 or so register it prints would indicate whether CPSR or XPSR is in use).

**Comment by mat-pr** [comment]
The output of the commands is as follows (I kept the same version of pwndbg, i.e. https://github.com/pwndbg/pwndbg/commit/00adfbbb5e06564f7d351624e09dae898f485c57)
```
pwndbg> show architecture 
The target architecture is set to "auto" (currently "armv7").
pwndbg> pi gdb.newest_frame().architecture().name()
'armv7'
pwndbg> info reg
r0             0x0                 0
r1             0x0                 0
r2             0x0                 0
r3             0x0                 0
r4             0x0                 0
r5             0x0                 0
r6             0x0                 0
r7             0x0                 0
r8             0x0                 0
r9             0x0                 0
r10            0x0                 0
r11            0x0                 0
r12            0x0                 0
sp             0x20010000          0x20010000
lr             0xffffffff          -1
pc             0x71c               0x71c <frame_dummy+756>
xpsr           0x41000000          1090519040
pwndbg>
```

The binary was compiled using [this cmake file](https://github.com/ECSC2024/openECSC-2024/blob/main/round-2/rev02/src/toolchain-arm-none-eabi.cmake) (the binary itself is [this one](https://github.com/ECSC2024/openECSC-2024/blob/main/round-2/rev02/attachments/arxelerated)).

**Comment by OBarronCS** [comment]
Thank you! That's very helpful. It looks like our detection of Cortex-M binaries is indeed incomplete and we need to work around limitations of GDB. For the time being, one can manually force the correct architecture and fix the bug by running `set architecture armv7e-m` in the session to tell GDB about the real architecture in use.

I did a lot of digging, and here's some stuff that is relevant (thinking out loud here):

Arm `Cortex-A` is the type of processor that executes the ARM-A profile (seen in desktops/servers), while `Cortex-M` is prevalent in microprocessors/devices with no operating system. Type-A has the `CPSR` register for flags, while Type-M has the `XPSR` register for flags (and the bug here is caused by us looking up `.cpsr` instead of `.xpsr`, which returns None as it doesn't exist for Type-M). The root cause of the bug is Pwndbg not being aware that we are debugging a Cortex-M binary.

Looking up the compiler path in the Makefile `arm-gnu-toolchain-13.2.Rel1-x86_64-arm-none-eabi` brings to a page saying it's for `bare-metal target`. I haven't found anything directly stating so on the internet so far, but I've gleaned that `bare-metal` implies Cortex-M.

Based on the output of the commands you ran, this fact (that it's compiled for Cortex-M targets/embedded systems) is not detected by GDB - it simply thinks its `ArmV7`, with no `-M`. Our current detection relies on the information given by GDB, and looks like there aren't any other GDB commands that might expose the remote architecture/cpu in a better way. Given this, we can implement checks of our own.

I thought of 3 possible fixes to detect M-Profile architecture:

1. Cortex-M binaries define a vector table at the start (with the first value being around 0x20000000 generally). We could look for this type of symbol and determines the architecture is M-Profile. The symbol name might not be stable, however.

![image](https://github.com/pwndbg/pwndbg/assets/55004530/28b75cce-1d75-43b9-81cd-d3a6c2459ea1)

2. Readelf outputs a "CPU_name" field that has `7-M` in it (as opposed to 7-A).
![image](https://github.com/pwndbg/pwndbg/assets/55004530/938b301c-f426-43cd-8535-63500ef7a869)

This would require access to the file.

3. Just query for a `CPSR` register or a `XPSR` register. If `XPSR` is present, is it Cortex-M. Honestly, this might be the most solid solution, and as far as I'm aware, it shouldn't fail (unless the XPSR register is present in cases I'm not aware of).

For anyone interested in trying it, can use the binary provided above (or get it from the GitHub, https://github.com/ECSC2024/openECSC-2024/tree/main/round-2/rev02), run it with `qemu-system-arm -cpu cortex-m3 -machine lm3s6965evb -kernel a
rxelerated -semihosting -semihosting-config enable=on,target=native -serial mon:stdio -S -s
 -nographic` and connect to it with gdb-multiarch.

**Comment by disconnect3d** [comment]
Let's go with the 3rd solution then? I don't see we can do better :(.

**Comment by OBarronCS** [comment]
Agreed - I'll make a PR implementing that solution. It might also be worth taking a peek at the GDB/qemu internals. GDB itself is clearly aware that this is an Cortex-M binary (because it knows to read the `xpsr` register), and qemu is probably exposing that somehow to GDB, just in no user-facing commands.

**Comment by disconnect3d** [comment]
@OBarronCS has this been fixed?

**Comment by OBarronCS** [comment]
The linked PR above fixes our detection of ARM Cortex mode 👍
