### ISSUE TITLE
Versioning and releases

### ISSUE THREAD

**Issue by disconnect3d** [pwndbg/pwndbg#229]
Hey,

Currently we are telling people to start using pwndbg on master branch, which is not really stable. This is also my fault, so I am sorry for the mess of making PRs into master.

One should either have:
* possibility to use some kind of "rolling-release" version, that would be an actual git repo with automatic git pull (e.g. every 24h)
* use working release of pwndbg

For the releases - I see we are currently having three tags which seems to be releases? Probably we should just use github releases: https://help.github.com/articles/creating-releases/

For a proper working release, we should for sure fix:
- IDA PRO synchronization issues https://github.com/pwndbg/pwndbg/issues/228 (there is PR for that)
- `add-symbol-file` is used incorrctly (actually it causes a segfault for remote PIE targets) - https://github.com/pwndbg/pwndbg/issues/177
- wrong parsing of elf headers for big endian targets - there is an issue for MIPS out there: https://github.com/pwndbg/pwndbg/issues/156 (there is PR for that, however it probably needs different implementation :P)
- wrong display of call targets: https://github.com/pwndbg/pwndbg/issues/112

and maybe some others.

We should also consider having some versioning scheme. I am not so much into the topic, but github release pages suggests [semantic versioning](http://semver.org/).

EDIT: Also maybe we should use more milestones and check out the `Projects` tab.

**Comment by zachriggle** [comment]
See the Milestones.  Technically I was supposed to cut a release sometime in April (2017.04).

**Comment by anthraxx** [comment]
just for the logs: I'm a very big fan of releases at points that we consider stable / release-worthy. :+1:

**Comment by zachriggle** [comment]
If we want "real" releases, I suggest we do what Pwntools currently does (ping @Idolf in case I'm wrong):

- There shall be three branches, `stable`, `beta`, and `dev`
- There shall *only* be three branches on the main repository (i.e., @zachriggle will need to do his development on a fork)
- Only bug-fixes will be merged into either `stable` or `beta`
- Every release, merges are cascaded `stable -> beta -> dev` so that merges are nice and easy
- After merging, a new minor-point-release (`1.X`) is created for `stable`
- After merging, a new beta minor-point-release (`1.Ybeta0`) is created for `beta`
- A new release occurs every ~month on a predetermined schedule
- Bugs *are not fixed* on releases older than the current `stable` (i.e. `0.9` is never fixed)
- Mid-cycle releases get a patch version bump (`1.1.X`) when bugs affecting `stable` or `beta` are found
- Pull Requests which fix bugs target the oldest branch they affect (e.g. `stable`).  We do not cherry pick individual fixes to individual branches

**Comment by Idolf** [comment]
Mostly correct.

- We do occasionally cherry-pick if something is fixed in a later branch and we don't notice/forget that it should really target an earlier branch.
- A new release occurs every 6 weeks on a predetermined schedule
- Only bugfixes that would actually affect users trigger new point releases. E.g. documentation fixes, travis fixes, CHANGELOG/README fixes, *tiny* fixes does not

**Comment by disconnect3d** [comment]
Hey,

So it has been few months after this discussion occured and we have this scheme of dev/beta/stable but the point is - we don't really use it that much. It seems that noone is using beta and probably a lot of people out there just use dev.

So my suggestion is to remove beta at all. We could also either keep stable or remove it and just make tags out of dev (or master or whatever we can rename it to) as probably noone is working on stable if it is not released/tagged (and so available through e.g. Arch User Repository).

**Comment by zachriggle** [comment]
I think the solution is to actually use the branches rather than abandon
them. There needs to be a supported long-term branch that receives bug
fixes and is not actively developed.

**Comment by disconnect3d** [comment]
I've decided to skip the `beta` branch as it probably wasn't used at all, even by me and I usually run on dev.

I will keep just two branches for now: dev and stable.

I have also added wiki and a page on how to make a release, so we won't have to remind ourselves how to do certain steps: https://github.com/pwndbg/pwndbg/wiki/Making-a-release

This being said I think the issue can be closed and so I am closing it ;).

**Comment by zachriggle** [comment]
The intent of the beta branch is not really that anybody uses it, but
rather to give commits some bake time before they hit stable.

I recommend sticking with a one-release delay (which is what the beta
branch is, effectively) so that bugs can be fixed before they hit general
release.

**Comment by disconnect3d** [comment]
This is a good idea but it introduces the need to update beta and dev separately... I think we can revisit this when we (hopefully) have more long-standing contributors.

**Comment by zachriggle** [comment]
The idea is that all bug-fixes will go into the oldest branch that's supported, and you just merge between them.  Merges for bugfixes should be ~painless.  `stable` -> `beta` merges should be extra painless.

In any case, you're doing all the work so I support your decision ❤️ I just wanted to provide context / justification for having the branch in the first place.
