### ISSUE TITLE
improve follow-fork-mode help text

### ISSUE THREAD

**Issue by k4lizen** [pwndbg/pwndbg#2318]
Currently
```
pwndbg> help set follow-fork-mode
Set debugger response to a program call of fork or vfork.
A fork or vfork creates a new process.  follow-fork-mode can be:
  parent  - the original process is debugged after a fork
  child   - the new process is debugged after a fork
The unfollowed process will continue to run.
By default, the debugger will follow the parent process.
```
**By default, the debugger will follow the parent process.**
But pwndbg overrides the gdb default and sets `follow-fork-mode` to `child`. 
https://github.com/pwndbg/pwndbg/blob/0dfcf7c0fe0d3ec6bb1060be32fc609fabfaddb0/pwndbg/dbg/gdb.py#L235

Could this help text be improved/clarified when pwndbg is running?

**Comment by disconnect3d** [comment]
Hi,

I don't think this is possible. We would have to overwrite the whole `set` command which would probably not work correctly since iirc we can't then execute the shadowed command.

Unless someone proves me wrong.

We do have a tip about that: https://github.com/pwndbg/pwndbg/blob/dev/pwndbg/lib/tips.py#L12 which we could probably improve?

**Comment by k4lizen** [comment]
> I don't think this is possible. We would have to overwrite the whole set command which would probably not work correctly since iirc we can't then execute the shadowed command.

Understandable, I figured that might be the case.

> We do have a tip about that: https://github.com/pwndbg/pwndbg/blob/dev/pwndbg/lib/tips.py#L12 which we could probably improve?

That'd be neat

**Comment by disconnect3d** [comment]
@k4lizen can u send a PR improving that? :)
