### ISSUE TITLE
previous chunks appear as allocated chunks when fastbin entries count exceeds 10

### ISSUE THREAD

**Issue by kunshim** [pwndbg/pwndbg#2376]
The following is my test code. Tested on ubuntu 24.04. 
```c
#include <stdio.h>

int main()
{
        char* buf[0x30];
        for (int i = 0; i < 0x30; i++)
                buf[i] = malloc(0x10);
        for (int i = 0; i < 0x30; i++)
                free(buf[i]);
        getchar();
}
```
when bp at getchar and use `heap` command, some chunks are shown as allocated chunk. 
Only latest freed chunks are shown as free chunk. 
![image](https://github.com/user-attachments/assets/1f9ba87c-f35f-436b-9007-0cdcd1161e8e)

**Comment by CptGibbon** [comment]
Could you try increasing the "heap-dereference-limit" configuration setting and see if the results are the same?

**Comment by kunshim** [comment]
Oh thank you. It was a stupid question.

**Comment by disconnect3d** [comment]
Shall we maybe warn the user we limited the results based on `heap-dereference-limit` when the results got limited?

**Comment by disconnect3d** [comment]
(also shall this be beyond this flag? maybe some `--limit=<sane default>` for all heap commands? idk)

cc: @k4lizen @CptGibbon

**Comment by k4lizen** [comment]
> Shall we maybe warn the user we limited the results based on heap-dereference-limit when the results got limited?

Yeah, it would be a good addition for sure.

> (also shall this be beyond this flag? maybe some --limit=<sane default> for all heap commands? idk)

I'm not sure I understand, you want a new flag which will override `heap-dereference-limit`? Could be useful. It would only affect the `heap` and `bins` family of commands I guess?

**Comment by CptGibbon** [comment]
Yes to both.

**Comment by disconnect3d** [comment]
I investigated this. The `heap-dereference-limit` does not influence the number of results printed by the `heap` command.

The `heap` command prints ALL chunks, no matter how many of them are there.

In the example shown in first post, the code allocates 30 chunks and then deallocates all of them. What happens is that first 7 deallocations end up in the tcachebin with size 0x20 and the rest of them are simply merged into the top chunk...

So in the end, we don't really need to do any printing regarding `heap-dereference-limit` since its not about it.

The `heap-dereference-limit` will make it so that e.g. smallbins will show `-> ...` when dereferencing further items of the linked list we reach the limit.

**Comment by CptGibbon** [comment]
@disconnect3d 

> I investigated this. The `heap-dereference-limit` does not influence the number of results printed by the `heap` command.

That is correct, however the issue here is which chunks are marked as free, not how many chunks the `heap` command prints.

 
> In the example shown in first post, the code allocates 30 chunks and then deallocates all of them. What happens is that first 7 deallocations end up in the tcachebin with size 0x20 and the rest of them are simply merged into the top chunk...

Incorrect, all chunks in this scenario end up in the tcache & fastbins.

Though I understand the confusion; if you let `getchar()` run then it will request enough memory to trigger fastbin consolidation, which is the reason we don't use functions like that in heap example programs, but the screenshot from the author shows the heap state before `getchar()` runs.

> So in the end, we don't really need to do any printing regarding `heap-dereference-limit` since it's not about it.

`heap-dereference-limit` does influence the number of chunks in a bin that are checked when assessing whether they're free in commands like `heap`, which was the original issue here.

**Comment by k4lizen** [comment]
The plot thickens.

So with the current implementation any chunk printed by `heap` that isn't marked as free, may very well be free?

If so that is pretty bad

**Comment by CptGibbon** [comment]
> So with the current implementation any chunk printed by `heap` that isn't marked as free, may very well be free?

Perhaps this affects `vis-heap-chunks` and the new code that marks pointers into free chunks in the disassembly, but I haven't checked.

One solution could be to warn the user when `heap-dereference-limit` is reached when using commands like `heap`.
