### ISSUE TITLE
rpm install  "Cannot convert between character sets `UTF-32` and `UTF-8`"

### ISSUE THREAD

**Issue by nietxan** [pwndbg/pwndbg#2392]
When installing rpm on f40 x86_64. Similar to this issue [https://github.com/pwndbg/pwndbg/issues/2323](url)
GNU gdb (Fedora Linux) 14.2-3.fc40

**Comment by disconnect3d** [comment]
Hi, this is a known issue that was fixed at some point. We will do a new release today or tomorrow so please stay tunned. :)

**Comment by disconnect3d** [comment]
@nietxan Fwiw you can also install the latest version from dev branch, but I would actually recommend waiting for the release and using that since we will get some major changes commited soon that may be a bit unstable for some time (This is because we are adding LLDB support and refactoring a lot of our APIs/code to make things debugger-agnostic).

In case you are in a rush and want a fast install, I could create a non-production release from the latest commit.

**Comment by nietxan** [comment]
It's okay thank you, I just didn't find any new mentions of this bug and hence reported
