### ISSUE TITLE
Warn user when heap-dereference-limit is reached while printing chunks

### ISSUE THREAD

**Issue by k4lizen** [pwndbg/pwndbg#2396]
A user which doesn't know about heap-dereference-limit can get confused when they only see 10 results, and its better UX even for those that do know about it.

As mentioned here: https://github.com/pwndbg/pwndbg/issues/2376#issuecomment-2296824323

**Comment by disconnect3d** [comment]
Considering this code: https://github.com/pwndbg/pwndbg/blob/6209c5b362ffe9f53125b478d1bf6f39f03db056/pwndbg/commands/heap.py#L181-L206

How is this limited? ;D

**Comment by disconnect3d** [comment]
_Closing this as we don't limit anything in the `heap` command output. Pasting a comment I wrote in #2376 about this here._

I investigated this. The `heap-dereference-limit` does not influence the number of results printed by the `heap` command.

The `heap` command prints ALL chunks, no matter how many of them are there.

In the example shown in first post, the code allocates 30 chunks and then deallocates all of them. What happens is that first 7 deallocations end up in the tcachebin with size 0x20 and the rest of them are simply merged into the top chunk...

So in the end, we don't really need to do any printing regarding `heap-dereference-limit` since its not about it.

The `heap-dereference-limit` will make it so that e.g. smallbins will show `-> ...` when dereferencing further items of the linked list we reach the limit.

**Comment by disconnect3d** [comment]
Now the question could be: do we want to have some limit for `heap` command? I would say: maybe.

Maybe it would be nice to have some flag like `--range <startaddr>:<endaddr>` so that only chunks between those addresses are printed? No idea. I think we can skip this for now unless someone really wants such feature.

**Comment by k4lizen** [comment]
A yeah good catch, I just figured that was the problem since the author of the original issue closed it. It was a bit weird to me that the same variable (`heap-dereference-limit`) would affect both `heap` and `bins` but I didn't look into it.

**Comment by CptGibbon** [comment]
Added a comment to #2376 explaining why the above assessment is incorrect.
