### ISSUE TITLE
Making docs connects to IDA

### ISSUE THREAD

**Issue by disconnect3d** [pwndbg/pwndbg#240]
### Description

Making the docs tries to connect to IDA. This probably isn't a big problem, however I believe it may produce some weird results in some situations (but probably nobody [except devs] makes the docs by him/herself :D).

### Steps to reproduce

1. Launch IDA Pro and load with whatever binary
2. Load ida_script.py in IDA
3. Go to pwndbg/docs
4. Fire e.g. `make html`

```
$ make html
Running Sphinx v1.5.5
Pwndbg successfully connected to Ida Pro xmlrpc: http://127.0.0.1:8888
Loaded 109 commands. Type pwndbg [filter] for a list.
```

PS: I am just reporting this, not going to work on this atm, please add `help wanted` and `someday`

**Comment by disconnect3d** [comment]
@zachriggle What do you think about adding an environment variable for IDA auto connecting like `PWNDBG_IDA_AUTO_CONNECT`? If the envvar isn't set we can just auto-connect.

This would let us to add `PWNDBG_IDA_AUTO_CONNECT=0` into makefile. 

Probably we should be adding environment variables into `pwndbg.envvars` module which would let us control what envvars do we use and where.

**Comment by zachriggle** [comment]
I like the idea, though I'd prefer to do it in the same way that `pwnlib.args` handles this.

http://docs.pwntools.com/en/stable/args.html

https://github.com/Gallopsled/pwntools/blob/stable/pwnlib/args.py

We can probably steal that entire module verbatim, though some of it won't quite be useful (since the `sys.argv` portion is fucked around with by GDB before we can look at it).

**Comment by gsingh93** [comment]
@disconnect3d was this still a problem the last time you built the docs?

**Comment by disconnect3d** [comment]
Nope, this has been resolved at some point but wasn't closed. Closing.
