### ISSUE TITLE
Setup on Kali Linux can't find python3.12

### ISSUE THREAD

**Issue by George-TL** [pwndbg/pwndbg#2427]
### Description

Master/main version of pwndbg fails to install under Kali Linux v2024.3 with the following error:
```
/usr/bin/python3.12: No such file or directory
```

There is only v3.11.9 of Python3 present on the system.

### Steps to reproduce

```
git clone https://github.com/pwndbg/pwndbg
cd ~/pwndbg
./setup.sh
cd ~
```
### My setup

kali-linux-2024.3
Python 3.11.9 (main, Apr 10 2024, 13:16:36) [GCC 13.2.0] on linux

### not a solution

After
`cd /usr/bin && ln -s python3.11 python3.12`
I can install pwndbg, but I wonder regards startup time
```
time gdb -ex "quit"
real    5.82s
user    5.57s
sys     0.26s
cpu     99%
```
Is this normal?

**Comment by patryk4815** [comment]
@George-TL Kali has broken `gdb`, try install `apt install python3.12` should solve problem

More context:
`gdb` on kali is wrongly builded for python3.12, but on system `python3` is python3.11

**Comment by disconnect3d** [comment]
Yeah, as @patryk4815 said, Kali made this weird decision that their system Python version is 3.11 while the GDB package is built with Python 3.12.

Regarding the startup time - we recently started refactoring Pwndbg to be debugger agnostic in order to support LLDB. This made some things a little bit slower, which we are going to optimize soon. However, your startup time is still like 2x longer than mine, so I think something is not right:

```
(.venv) root@pwndbg:~# time gdb -ex "quit"
pwndbg: loaded 166 pwndbg commands and 47 shell commands. Type pwndbg [--shell | --all] [filter] for a list.
pwndbg: created $rebase, $base, $bn_sym, $bn_var, $bn_eval, $ida GDB functions (can be used with print/break)

real	0m2.876s
user	0m1.983s
sys	0m0.342s
(.venv) root@pwndbg:~# time gdb -ex "quit"
pwndbg: loaded 166 pwndbg commands and 47 shell commands. Type pwndbg [--shell | --all] [filter] for a list.
pwndbg: created $rebase, $base, $bn_sym, $bn_var, $bn_eval, $ida GDB functions (can be used with print/break)

real	0m2.655s
user	0m1.878s
sys	0m0.247s
(.venv) root@pwndbg:~# time gdb -ex "quit"
pwndbg: loaded 166 pwndbg commands and 47 shell commands. Type pwndbg [--shell | --all] [filter] for a list.
pwndbg: created $rebase, $base, $bn_sym, $bn_var, $bn_eval, $ida GDB functions (can be used with print/break)

real	0m2.542s
user	0m1.887s
sys	0m0.227s
(.venv) root@pwndbg:~# time gdb -ex "version" -ex "quit"
pwndbg: loaded 166 pwndbg commands and 47 shell commands. Type pwndbg [--shell | --all] [filter] for a list.
pwndbg: created $rebase, $base, $bn_sym, $bn_var, $bn_eval, $ida GDB functions (can be used with print/break)
Gdb:      14.0.50.20230907-git
Python:   3.11.6 (main, Apr 10 2024, 17:26:07) [GCC 13.2.0]
Pwndbg:   2024.08.29 build: 5d95e98c
Capstone: 5.0.1280
Unicorn:  2.0.1
```

Now, to sum up:
1. You should be able to solve your problem by installing `python3.12` on your system, so that our setup can use that as its virtual environment.
2. If this does not work, you can build your own GDB against your Python 3.11 [as descibed in our README](https://github.com/pwndbg/pwndbg/blob/5d95e98c78265a4c47813101809eb9cb4b9a8d15/README.md#L64-L71) and then our setup should work.
3. Alternatively, you can use a portable release archive `*-portable.tar.gz` from our recent release: https://github.com/pwndbg/pwndbg/releases/tag/2024.08.29 - iirc this contains a `pwndbg` binary/script that should work out of the box (it contains ALL dependencies inside).

If you have time and can help us then we would appreciate if:
- you can send a PR to improve setup.sh to detect such python version mismatch and inform user how to fix it
- you can investigate the startup time issue and report it to us and help us optimize things -- we will of course do it ourselves too, its just not in our very first priority for now

I am closing this for now, please let us know if there is anything else we can do to help here.

**Comment by George-TL** [comment]
Installing Python 3.12 solved setup issue - thank you.
I've used following commands:
```
sudo apt-get update
sudo apt-get install -y python3.12 python3.12-venv
```
As for startup time I've moved to:
- Intel(R) Core(TM) i5-6300U CPU @ 2.40GHz
- VirtualBox-6.1

and see big difference:
```
$ time gdb -ex "quit"
real    1.00s
user    0.88s
sys     0.12s
cpu     99%
```
Looks like other hardware with VirtualBox 7.1.0 installed might be source of problem.

**Comment by George-TL** [comment]
Yup, there is a big performance regression:
```
VirtualBox 7.0 - real 1.50s
VirtualBox 7.1 - real 5.82s
```

**Comment by disconnect3d** [comment]
What is this output? Which GDB and Pwndbg versions are those? What machine do you run it on? How did u install? :P

**Comment by George-TL** [comment]
Output shows pwndbg startup times in specified VB versions.
For that particular test host is "Intel(R) Core(TM) i5-3470 CPU @ 3.20GHz" with Windows 10 OS.
There are other problems with new VirtualBox too. For example slow network throughput (virtio-net+nat scenario).
@disconnect3d I don't think you want to troubleshoot VB regression...

**Comment by disconnect3d** [comment]
Yeah, I don't think we can do anything with VB performance. I bet this is related to some slower drive access or something? Maybe they do something similar as WSL2 on Linux where access to -- iirc -- mounted host/windows drive is super slow. I don't know.

**Comment by George-TL** [comment]
Update

`Intel(R) Core(TM) i5-3470 CPU @ 3.20GHz`
`Microsoft Windows [Version 10.0.19045.5608]`
`VirtualBox 7.1.6`
`Kali Linux 2025.1a`

```
pwndbg> version
Pwndbg:   2025.02.19 build: f9a37606
Python:   3.13.2 (main, Feb  5 2025, 01:23:35) [GCC 14.2.0]
GDB:      16.2
Capstone: 5.0.5
Unicorn:  2.1.3
Pwnlib:   4.14.0
```

```
time gdb -ex "quit"
real    1.79s
user    1.66s
sys     0.12s
cpu     99%
````
Looks much better now.
