### ISSUE TITLE
`ctx disasm` throws exception when attached to remote Windows gdbserver

### ISSUE THREAD

**Issue by sudoBash418** [pwndbg/pwndbg#2467]
### Description

`pwndbg` throws a `ValueError: Bad register` exception when running `ctx disasm`.
This seems to happen whenever I'm connected to a Windows `gdbserver` - I saw the same behaviour with Wine-Staging 9.10 and a Windows 10 VM.

This issue does not occur with the `2024.02.14` release.

<details>
<summary>Traceback</summary>

```
Traceback (most recent call last):
  File "/tmp/pwndbg/pwndbg/gdblib/regs.py", line 40, in gdb_get_register
    return frame.read_register(name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: Bad register

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/tmp/pwndbg/pwndbg/commands/__init__.py", line 187, in __call__
    return self.function(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/tmp/pwndbg/pwndbg/commands/context.py", line 641, in context
    func(
  File "/tmp/pwndbg/pwndbg/commands/context.py", line 312, in _serve_context_history
    current_output = function(*a, **kw)
                     ^^^^^^^^^^^^^^^^^^
  File "/tmp/pwndbg/pwndbg/commands/context.py", line 866, in context_disasm
    result = pwndbg.aglib.nearpc.nearpc(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/tmp/pwndbg/pwndbg/aglib/nearpc.py", line 142, in nearpc
    instructions, index_of_pc = pwndbg.aglib.disasm.near(
                                ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/tmp/pwndbg/pwndbg/aglib/disasm/__init__.py", line 387, in near
    emu = pwndbg.emu.emulator.Emulator()
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/tmp/pwndbg/pwndbg/emu/emulator.py", line 251, in __init__
    value = getattr(pwndbg.gdblib.regs, reg)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/tmp/pwndbg/pwndbg/lib/cache.py", line 162, in decorator
    value = func(*a, **kw)
            ^^^^^^^^^^^^^^
  File "/tmp/pwndbg/pwndbg/gdblib/regs.py", line 237, in fsbase
    return self._fs_gs_helper("fs_base", ARCH_GET_FS)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/tmp/pwndbg/pwndbg/lib/cache.py", line 162, in decorator
    value = func(*a, **kw)
            ^^^^^^^^^^^^^^
  File "/tmp/pwndbg/pwndbg/gdblib/regs.py", line 250, in _fs_gs_helper
    reg_value = gdb_get_register(regname)
                ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/tmp/pwndbg/pwndbg/gdblib/proc.py", line 186, in wrapper
    return func(*a, **kw)
           ^^^^^^^^^^^^^^
  File "/tmp/pwndbg/pwndbg/gdblib/regs.py", line 42, in gdb_get_register
    return frame.read_register(name.upper())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: Bad register
```

</details>

---

The cause of the exception seems to be an assumption that the `fsbase` and `gsbase` registers are available.  
When connected to a Windows `gdbserver`, this appears to be false:
```
>>> list(reg.name for reg in gdb.selected_frame().architecture().registers() if 'base' in reg.name)
[]
```

Running a native binary on Linux shows the registers (and works as expected):
```
>>> list(reg.name for reg in gdb.selected_frame().architecture().registers() if 'base' in reg.name)
['fs_base', 'gs_base']
```

I'm not sure why `fsbase`/`gsbase` are not available with this setup, but FWIW I've been able to workaround the issue by adding a try-except to the register access in `_fs_gs_helper`:
```patch
--- a/pwndbg/gdblib/regs.py
+++ b/pwndbg/gdblib/regs.py
@@ -246,7 +246,11 @@ class module(ModuleType):
         Requires ptrace'ing the child directory if i386."""
 
         if pwndbg.aglib.arch.name == "x86-64":
-            reg_value = gdb_get_register(regname)
+            try:
+                reg_value = gdb_get_register(regname)
+            except ValueError:
+                # gdbserver under Windows does not expose `fsbase` / `gsbase` registers
+                return 0
             return int(reg_value) if reg_value is not None else 0
 
         # We can't really do anything if the process is remote.
```

Not sure if this is the best solution, or if `pwndbg` is even the place to solve this issue.

### Steps to reproduce

1. Run `wine /usr/x86_64-w64-mingw32/bin/gdbserver.exe 127.0.0.1:12345 target.exe` in the background
2. Connect using pwndbg: `gdb --exec=target.exe -iex 'target extended-remote 127.0.0.1:12345'`
3. Run `ctx disasm` (or just `fsbase`)

### My setup

Local (Arch Linux, x86_64):
```shell
pwndbg> version
Gdb:      15.1
Python:   3.12.6 (main, Sep  8 2024, 13:18:56) [GCC 14.2.1 20240805]
Pwndbg:   2024.08.29 build: 686e93e0
Capstone: 5.0.1280
Unicorn:  2.0.1
```

Remote (also tested in a Windows 10 VM w/ `gdbserver 15.2`):
```shell
$ wine /usr/x86_64-w64-mingw32/bin/gdbserver.exe --version
GNU gdbserver (GDB) 14.2
Copyright (C) 2023 Free Software Foundation, Inc.
gdbserver is free software, covered by the GNU General Public License.
This gdbserver was configured as "x86_64-w64-mingw32"
$ wine --version
wine-9.10 (Staging)
```

**Comment by disconnect3d** [comment]
Considering all the logic of fs/gs getter:
https://github.com/pwndbg/pwndbg/blob/eccfd91d869598496fa9f10c10f2429a656a5ff9/pwndbg/gdblib/regs.py#L245-L271

I wonder if this order is correct. Why do we allow for getting the reg on x86-64 AND remote? Perhaps this:
```py
        # We can't really do anything if the process is remote.
        if pwndbg.gdblib.remote.is_remote():
            return 0
```
should be moved above the if check with x86-64?

**EDIT: No.**

**Comment by disconnect3d** [comment]
Fwiw on gdbserver on linux:
```
pwndbg> pi [reg.name for reg in gdb.selected_frame().architecture().registers()]
['rax', 'rbx', 'rcx', 'rdx', 'rsi', 'rdi', 'rbp', 'rsp', 'r8', 'r9', 'r10', 'r11', 'r12', 'r13', 'r14', 'r15', 'rip', 'eflags', 'cs', 'ss', 'ds', 'es', 'fs', 'gs', 'st0', 'st1', 'st2', 'st3', 'st4', 'st5', 'st6', 'st7', 'fctrl', 'fstat', 'ftag', 'fiseg', 'fioff', 'foseg', 'fooff', 'fop', 'mxcsr', 'fs_base', 'gs_base', 'ymm0', 'ymm1', 'ymm2', 'ymm3', 'ymm4', 'ymm5', 'ymm6', 'ymm7', 'ymm8', 'ymm9', 'ymm10', 'ymm11', 'ymm12', 'ymm13', 'ymm14', 'ymm15']

pwndbg> pi gdb.selected_frame().read_register('fs_base')
<gdb.Value object at 0x7f49dd4d9c70>

pwndbg> pi int(gdb.selected_frame().read_register('fs_base'))
0
```

On versions:
```
pwndbg> version
Gdb:      14.0.50.20230907-git
Python:   3.11.6 (main, Apr 10 2024, 17:26:07) [GCC 13.2.0]
Pwndbg:   2024.08.29 build: 686e93e0
Capstone: 5.0.1280
Unicorn:  2.0.1

(.venv) root@pwndbg:~# gdbserver --version
GNU gdbserver (Ubuntu 14.0.50.20230907-0ubuntu1) 14.0.50.20230907-git
Copyright (C) 2023 Free Software Foundation, Inc.
gdbserver is free software, covered by the GNU General Public License.
This gdbserver was configured as "x86_64-linux-gnu"
```

**Comment by disconnect3d** [comment]
I guess the order of checking x86-64 -> checking remote -> ptrace for x86 makes sense.

I don't know why gdbserver on windows does not expose this register, but, we can fix it in two ways:

1. We can do the fix you suggested.
2. We could have checked if fs_base/gs_base is in the gdb registers list, cache that list until new program is launched, and use that?
3. We could update this:
```py
@pwndbg.gdblib.proc.OnlyWhenRunning
def gdb_get_register(name: str, frame: gdb.Frame | None = None) -> gdb.Value | None:
    if frame is None:
        frame = gdb.selected_frame()
    try:
        return frame.read_register(name)
    except ValueError:
        return frame.read_register(name.upper())
```
So that the `except ValueError:` has another `try: ... except ValueError:` and warns user (once) that the register hasn't been found but a value of 0 will be returned?


The last solution would fix similar Pwndbg-crashing problems in the future, of course its still not great, but it would not crash the whole Pwndbg?

cc: @gsingh93 @OBarronCS @CptGibbon thoughts?

**Comment by OBarronCS** [comment]
Did some digging - looks like the gs/fs registers are not exposed to user space programs in Windows the same way they are in Linux. Couldn't find too much information on the details, but there's a comment in a GDB patch about this - https://sourceware.org/pipermail/gdb-patches/2018-June/150039.html#:~:text=Since%20Windows%20doesn't%20expose%20these%20to%20userspace

Looks like some more recent changes to Windows allow the fs/gsbase registers to optionally be available depending on a feature flag, but looking into the GDB source code indicates this is not in use - https://gist.github.com/merryhime/f22e75d5128c07d77630ca01c4272937

In terms of a solution, I think that there is new code during the additions for LLDB that might already fix this:

The new aglib `get_register` has the following code:
https://github.com/pwndbg/pwndbg/blob/f945b417da14c5bafdc41e6c0c38d83100501e0d/pwndbg/aglib/regs.py#L39-L50

The `by_name` for GDB is here: https://github.com/pwndbg/pwndbg/blob/f945b417da14c5bafdc41e6c0c38d83100501e0d/pwndbg/dbg/gdb.py#L78-L85

The aglib version of getting register would return `None` instead of crashing, I believe. It's just that currently, as seen in the tracebook in the post, the codeflow is calling the `gdb_get_register` seen in the previous comment. I'm not sure if this function will eventually get removed, and the aglib version used instead, which will not have crashes but instead return `None` on failure.

**Comment by disconnect3d** [comment]
Fixed by https://github.com/pwndbg/pwndbg/pull/2478 ! Thanks! :)
