### ISSUE TITLE
`ctxp` doesn't work when `cwatch execute 'p var'`

### ISSUE THREAD

**Issue by BigBrotherJu** [pwndbg/pwndbg#2579]
### Description

If I `cwatch execute 'p/z var'`, `ctxp` doesn't work correctly. 

After I `cwatch execute 'p/z var'`, everytime I `ctxp`, the history number just increases like this: 17/18, 18/19, 19/20, 20/21. The output of `p/z var` also changes from `$39 = 0x00010001` to `$40 = 0x00010001`.

Seems like the proper context history is not used, and `p/z var` is executed over and over again.

The correct behavior is to retrieve the proper context history instead of executing commands. 

### Steps to reproduce

1. Debug any binary with GDB.
2. `start`
3. `cwatch execute 'p var'`
4. `ctxp`
5. Problem occurs

### My setup

```
pwndbg> version
Gdb:      13.1
Python:   3.11.2 (main, Mar 13 2023, 12:18:29) [GCC 12.2.0]
Pwndbg:   2024.08.29 build: 64bd3fee
Capstone: 5.0.1280
Unicorn:  2.1.0
```

**Comment by peace-maker** [comment]
The problem is with this code

https://github.com/pwndbg/pwndbg/blob/ce954f74489cf5849cee509d541c7d9255a9cd82/pwndbg/commands/context.py#L312-L318

It checks if the current context section is already at the top of the history stack and adds it otherwise. This is run everytime the context is displayed even if no new event happened which could have changed the state. This is fine for other views like disasm, but when evaluating expressions in cwatch gdb changes the `$39`/`$40` variable names making the output look like new data appeared.

The current approach of always rendering the newest context even while wanting to display a cached context from the history isn't ideal, especially for slow remote targets. I just don't know which events to hook to know if the context output might have changed. Just a prompt_hook doesn't help, since the data might not have been modified. Can all possible reasons the context output change be covered by [events](https://sourceware.org/gdb/current/onlinedocs/gdb.html/Events-In-Python.html#Events-In-Python)? `memory_changed` and `register_changed` seem obvious, but are those fired after continue/stepping too?

**Comment by disconnect3d** [comment]
The `memory_changed` and `register_changed` events are only fired when you change the register from within GDB.

I am not sure what the `serve_context_history`, would have to dig it up, but maybe we should either revert the history or disable it by default and try to fix it with tests etc?

**Comment by disconnect3d** [comment]
I mean, there are a few issues that occured recently regarding the context history feature. Or: any chance u could track down those issues @peace-maker ? :<

**Comment by peace-maker** [comment]
Were there more than this issue?
