### ISSUE TITLE
Slowdown on every command under WSL

### ISSUE THREAD

**Issue by ChibiDenDen** [pwndbg/pwndbg#288]
Under WSL (windows subsystem for linux) pwndbg works just fine, but every action is really slow.
strace on gdb shows a lot of socket connection attempts on TCP localhost:8888 that ends with connection refused.
by looking at your code, the connection is made for the IDA RPC.

It seems that the time it takes for a connection to be refused under WSL is not negligible and this badly affects pwndbg.

I fixed it temporarily by changing withIDA.__call__ to just return None.

please consider avoiding repeated failed attempts on  IDA RPC to improve performance on WSL (and maybe other linux distros as well).

**Comment by zachriggle** [comment]
I'd recommend creating a Pull Request to fix this functionality ❤️ 

I expect that this can be resolved by:

1. Adding a timeout to the socket connection operation when it's set to localhost (say 50ms)
2. Memoizing the results of the socket connection attempt, so that it happens less frequently (I'd suggest `pwndbg.memoize.reset_on_cont`)

**Comment by zachriggle** [comment]
It looks like this was effectively resolved by adding a timeout in 124e997555629cb76eb9db7a215e0bb1f1f894a3
