### ISSUE TITLE
Show ARM/Thumb mode (Feature request)

### ISSUE THREAD

**Issue by techvoltage** [pwndbg/pwndbg#292]
Would like to know whether I'm running in ARM/Thumb mode in gdb

**Comment by disconnect3d** [comment]
Isn't it known from the instructions itself or from $cpsr (or $xpsr on some ARMs) register?

Anyway, getting the value is pretty easy - we do parse it actually just for $cpsr (so yeah, ARMs with $xpsr are not handled at all as decribed here https://github.com/pwndbg/pwndbg/issues/264) in here: https://github.com/pwndbg/pwndbg/blob/dev/pwndbg/disasm/__init__.py#L86-L87

I would probably go with adding a `pwndbg.arch.mode` which would be `'ARM'` or `'THUMB'` for ARMs and just `None` for other archs.

The question is - where do we want to display it?

One idea would be displaying it in the `DISASM` bar, e.g. instead of:
`[──────────DISASM──────────]`

We can display:
`[──────────DISASM  - ARM MODE──────────]`

This DISASM banner can be changed easily, just change the string in here https://github.com/pwndbg/pwndbg/blob/dev/pwndbg/commands/context.py#L154.

As this is rather an easy enhancement, would you try to add it @techvoltage? :)

**Comment by techvoltage** [comment]
Now that you've specified the how and where, would be glad to work on it!

**Comment by zachriggle** [comment]
If the address is odd, it's Thumb.

**Comment by disconnect3d** [comment]
Just for reference: we had a PR for that in https://github.com/pwndbg/pwndbg/pull/293 but it haven't been merged finally.

**Comment by disconnect3d** [comment]
Done in #2281
