### ISSUE TITLE
Disassemble command highlight/color

### ISSUE THREAD

**Issue by FFY00** [pwndbg/pwndbg#370]
Hi, is it possible to add highlight/color to the disassemble command? If not, it is possible to create a new command with it enabled?

Thanks,
Filipe

**Comment by FFY00** [comment]
Looks like the only command available is pdisass which only shows a portion of the code.

**Comment by disconnect3d** [comment]
@FFY00 you mean `x/10i <address or expression>` and `disassemble <symbol>`?
We could potentially override `disassemble` to `u`/`pdisass` (those are aliases).

I know also that @anthraxx was working on adding pygments (?) or some other asm syntax highlighting to pwndbg but it didn't get a PR

**Comment by FFY00** [comment]
Yes, exactly.

**Comment by anthraxx** [comment]
Oh right, got catched by RL lately. I still have my branch nearly finished just polishing left. Will finalize during 34C4 and send the PR 😎

**Comment by disconnect3d** [comment]
@anthraxx maybe some pair programming on 34c3 :D

**Comment by cebrusfs** [comment]
I have wrote my own version syntax highlight feature in my fork version. Since I thought it will conflict with current design and the UI changes sometimes are not welcome, so I put it at my own version's fork.

However, I wrote this code 2 years ago, it may violate some current design. Last week, I spent some time to rebase the code to current `dev` branch and have not test too much yet. (It may only work on my environment)

My current design is
1. create a syntax highlight function, given the code text and the language or filename, then return the highlighted code.
2. ASM syntax highlight: `pwndbg/color/disasm.py:instruction()` use that function to syntax highlight *each instructions*. Some issues are open now.
    1. To highlight all the instructions at one time?
    2. How to detect the intel or arm asm?
        1. get the arch from pwndbg.arch?
        1. pass a parameter when call `instruction(arch=)`
3. Source highlight: we can not highlight partial of code. The current `context_code` implementation use `list <line_num>` will not works. My current solution is use
    ```python
    sal = gdb.selected_frame().find_sal()
    filename = sal.symtab.fullname()
    ```
    to get the path of current frame's source code and then open the whole file to syntax highlight the full code and cache it. Then, `context_code` fetch the lines it want.
However, I don't know how gdb get the source code path and whether this API will broken in some cases. You can think it is a kind of workaround since it was just for my personal use.

    UPDATE: use the filename to detect the language will not work in some cases. For example, I write arm asm use `.S` extension but in pygments will use `GasLexer` (AT&T asm) to parse the `.S` file by default.

If you are interesting, you can see the commit whose title starts with "Syntax Highlight" at [my UI fork](https://github.com/cebrusfs/217gdb/commits/master). BTW, I will force push to master branch sometimes, since I always rebase my customized commits to the lastest code base.

I am also glad to create a draft PR if you want to base on my design to implement this feature.

**Comment by zachriggle** [comment]
Pwntools `pwn disasm` command already provides syntax highlighting via Pygments.

https://github.com/Gallopsled/pwntools/blob/5c4def05b28fb121124acb37c2b567b313ad3bff/pwnlib/commandline/disasm.py#L72-L90

https://github.com/Gallopsled/pwntools/blob/5c4def05b28fb121124acb37c2b567b313ad3bff/pwnlib/lexer.py

We can probably just use those.  It works for pretty much all architectures, though it is designed to colorize the byte patterns as well (it operates on objdump's output).

Here's how it looks for Intel and ARM:

<img width="399" alt="screen shot 2018-01-03 at 3 48 16 pm" src="https://user-images.githubusercontent.com/111640/34541425-bc4f3a88-f09d-11e7-96ec-b136fb4e8b1f.png">
<img width="168" alt="screen shot 2018-01-03 at 3 49 14 pm" src="https://user-images.githubusercontent.com/111640/34541429-be969aac-f09d-11e7-8f94-dc2e101125f8.png">

We could extend the lexer to also recognize branch instructions and colorize them differently.

**Comment by cebrusfs** [comment]
Ok. It seems that we can pass all asm code to pwnlib lexer. For the source code part, we still use filename to detect the language.

@disconnect3d @anthraxx
It seems that you were working on this. What's your progress? If you almost finish your PR, I will not involve this.

**Comment by disconnect3d** [comment]
@cebrusfs @anthraxx had some progress on it but it was some time ago and since your PR is first... :P ;)

Thanks for contributing :heart:

**Comment by cebrusfs** [comment]
Hi @FFY00, my PR is merged, can you check for this? Any feedback is welcome :)

**Comment by FFY00** [comment]
Hi @cebrusfs, thanks for all the work. I'm very busy write now but as soon as I can, I will check it.
