### ISSUE TITLE
ida.py, ida-script uses deprecated API

### ISSUE THREAD

**Issue by zachriggle** [pwndbg/pwndbg#738]
The current implementation of the IDA Pro bindings in Pwndbg rely on the old, now-deprecated API.  The new API is available in all IDA versions since v7.0:
https://www.hex-rays.com/products/ida/7_0/docs/api70_porting_guide/

IDA v7.4 disables the compatibility layer by default, meaning the `pwndbg.ida` module is now broken as well as `ida_script.py` hosting the XMLRPC server.

HexRays has written an API porting guide that should assist in the process:
https://www.hex-rays.com/products/ida/support/ida74_idapython_no_bc695_porting_guide.shtml

Since the free version of IDA is now v7.0, I do not recommend trying to keep mutual compatibility between versions.  IDA Pro v7.0 was released in Feb 2018, so most people have likely updated by now.

**Comment by disconnect3d** [comment]
TL;DR: Closing all IDA integration issues for now. We implemented Binja integration recently and an abstraction for `IntegrationProvider`. I would be happy of accepting a new version of IDA sync if anyone is interested in implementing it (since the old script and code most likely do not work at all).

https://github.com/pwndbg/pwndbg/issues/218#issuecomment-2518778108
