### ISSUE TITLE
Skip endbr64 and endbr32 instructions

### ISSUE THREAD

**Issue by zachriggle** [pwndbg/pwndbg#802]
In this screenshot borrowed from another Pull Request, there are a bunch of `endbr64` instructions that are shown in the telescope.

This information is generally not useful, we should have a default-off setting to fetch the "next" instruction if this is encountered.  Not sure if this is actually a good idea, just something I noticed.

![](https://user-images.githubusercontent.com/10009354/85929449-471e9780-b8b5-11ea-86c6-d4191845f781.png)

**Comment by disconnect3d** [comment]
I think it would be misleading to show next instruction for a given address. How would we mark that?

Also, while those instruction currently do nothing (act like `nop`), they will do *something* when [Intel (finally) delivers CET support in CPUs which should happen soon™](https://www.phoronix.com/scan.php?page=news_item&px=Intel-CET-Tiger-Lake).

When those instructions will actually do something, displaying them instead of others might be crucial for developing exploits.

**Comment by zachriggle** [comment]
Good points!
