### ISSUE TITLE
CI is currently broken

### ISSUE THREAD

**Issue by zachriggle** [pwndbg/pwndbg#805]
Travis CI is showing an error report currently:
https://travis-ci.org/pwndbg/pwndbg

It's not clear what we're testing, or if we are just testing installation, but it should probably be resolved and hopefully is easy to do.

**Comment by disconnect3d** [comment]
Also: we should move to GitHub actions.

**Comment by airvzxf** [comment]
It was solved in the PR: https://github.com/pwndbg/pwndbg/pull/868. We can close this issue if all of you are agreed.

We have an opportunity for improvement. I noticed that the lint is checking the alphabetic order of the imports, we could add some automatization to sort the order in between the CI/actions are running. For example, in these both request the CI fails because the order of the imports.
https://github.com/pwndbg/pwndbg/pull/874/checks
https://github.com/pwndbg/pwndbg/pull/870/checks

**Comment by disconnect3d** [comment]
Ugh, I should have closed that long time ago. The CI is already fixed and is now working on GH actions.

What I want to do further is to run CI on three different Ubuntu versions: 22.04, 20.04 and 18.04 which I started working on in here: https://github.com/pwndbg/pwndbg/pull/1076 but it turns out that it triggers some weird bugs that we have to look into.

Anyway, closing this one finally :-)
