### ISSUE TITLE
IDA Integration: Dynamic type reconstruction / compilation

### ISSUE THREAD

**Issue by zachriggle** [pwndbg/pwndbg#847]
Given an a structure definition from IDA Pro, it should be possible to dynamically recreate a type as a C structure (with generally good fidelity, and do so recursively for nested structs) and compile to a dummy `.o` or ELF and import that into Pwndbg.

This will allow users to declare structs in IDA Pro, and use them directly within Pwndbg with GDB's standard syntax.

```
pwndbg> p *(some_ida_type*)0xdeadbeef
```

**Comment by disconnect3d** [comment]
TL;DR: Closing all IDA integration issues for now. We implemented Binja integration recently and an abstraction for `IntegrationProvider`. I would be happy of accepting a new version of IDA sync if anyone is interested in implementing it (since the old script and code most likely do not work at all).

https://github.com/pwndbg/pwndbg/issues/218#issuecomment-2518778108
