### ISSUE TITLE
IDA Integration: Expand known function arguments with IDA Pro function signatures varnames

### ISSUE THREAD

**Issue by zachriggle** [pwndbg/pwndbg#848]
In IDA Pro, you can specify the signature for a function by hitting the `Y` key.

If IDA Pro integration is enabled, we should be able to supplement `pwndbg.functions` with this information dynamically at runtime.

**Comment by disconnect3d** [comment]
Closing for now.TL;DR: Closing all IDA integration issues for now. We implemented Binja integration recently and an abstraction for `IntegrationProvider`. I would be happy of accepting a new version of IDA sync if anyone is interested in implementing it (since the old script and code most likely do not work at all).

https://github.com/pwndbg/pwndbg/issues/218#issuecomment-2518778108
