### ISSUE TITLE
An error occurred with the pwngdb plug-in for gdb10.2

### ISSUE THREAD

**Issue by D1ag0n-Young** [pwndbg/pwndbg#920]
Traceback (most recent call last):
  File "~/pwndbg-src/gdbinit.py", line 24, in <module>
    import pwndbg # isort:skip
  File "/root/pwndbg-src/pwndbg/__init__.py", line 7, in <module>
    import pwndbg.android
  File "/root/pwndbg-src/pwndbg/android.py", line 5, in <module>
    import pwndbg.color.message as message
  File "/root/pwndbg-src/pwndbg/color/__init__.py", line 7, in <module>
    import pwndbg.memoize
  File "/root/pwndbg-src/pwndbg/memoize.py", line 36
    print("Cannot memoize %r!", file=sys.stderr)
                                    ^
SyntaxError: invalid syntax

What is the cause of this？

**Comment by disconnect3d** [comment]
Can you show an output of this command in gdb?:

    pi import sys; print(sys.version)

**Comment by D1ag0n-Young** [comment]
Traceback (most recent call last):
  File "~/pwndbg/gdbinit.py", line 24, in <module>
    import pwndbg # isort:skip
  File "/root/pwndbg/pwndbg/__init__.py", line 7, in <module>
    import pwndbg.android
  File "/root/pwndbg/pwndbg/android.py", line 5, in <module>
    import pwndbg.color.message as message
  File "/root/pwndbg/pwndbg/color/__init__.py", line 7, in <module>
    import pwndbg.memoize
  File "/root/pwndbg/pwndbg/memoize.py", line 36
    print("Cannot memoize %r!", file=sys.stderr)
                                    ^
SyntaxError: invalid syntax
(gdb) pi import sys; print(sys.version)
2.7.12 (default, Mar  1 2021, 11:38:31) 
[GCC 5.4.0 20160609]

Is it the python version? How to change it?

**Comment by D1ag0n-Young** [comment]
@disconnect3d

**Comment by disconnect3d** [comment]
Can you try this withotu loading pwndbg?

**Comment by disconnect3d** [comment]
Ah you did it. I think this may be it

**Comment by disconnect3d** [comment]
You would need to build gdb from sources and tell it to use python 3

**Comment by D1ag0n-Young** [comment]
GNU gdb (GDB) 10.2
Copyright (C) 2021 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html&gt;
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "x86_64-pc-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<https://www.gnu.org/software/gdb/bugs/&gt;.
Find the GDB manual and other documentation resources online at:
&nbsp; &nbsp; <http://www.gnu.org/software/gdb/documentation/&gt;.


For help, type "help".
Type "apropos word" to search for commands related to "word".
(gdb) pi import sys; print(sys.version)
2.7.12 (default, Mar&nbsp; 1 2021, 11:38:31)&nbsp;
[GCC 5.4.0 20160609]





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "pwndbg/pwndbg"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年5月13日(星期四) 晚上7:49
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [pwndbg/pwndbg] An error occurred with the pwngdb plug-in for gdb10.2 (#920)





 
Can you try this withotu loading pwndbg?

**Comment by disconnect3d** [comment]
You can do it more or less like below, ofc it assumes you are in a directory with gdb downloaded.

Note that some of this can be changed if needed. E.g. `--enable-targets=all` builds GDB so it supports ALL targets/architectures (e.g. for remote debugging). Please refer to GDB docs if you need help with those flags.

```
mkdir build
cd build
../configure --disable-nls --disable-werror --with-system-readline --with-python=/usr/bin/python3.9 --with-system-gdbinit=/etc/gdb/gdbinit --enable-targets=all
make -j7
```

EDIT: oh, after this I believe that `make install` would install the built GDB somewhere in your system (`/usr/local/bin` most likely?) The install directory can probably be changed by passing in `--with-prefix=<path>`

EDIT2: Oh, this may actually be `--prefix` instead of `--with-prefix` - I am not sure (maybe there is `./configure --help` to check this?), at least https://askubuntu.com/questions/891835/what-does-prefix-do-exactly-when-used-in-configure suggests it may be `--prefix`

**Comment by D1ag0n-Young** [comment]
Is there a requirement for python version? My local is python3.5.2




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年5月13日(星期四) 晚上7:56
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [pwndbg/pwndbg] An error occurred with the pwngdb plug-in for gdb10.2 (#920)





 
You can do it more or less like below, ofc it assumes you are in a directory with gdb downloaded.
 
Note that some of this can be changed if needed. E.g. --enable-targets=all builds GDB so it supports ALL targets/architectures (e.g. for remote debugging).
 mkdir build cd build ../configure --disable-nls --disable-werror --with-system-readline --with-python=/usr/bin/python3.9 --with-system-gdbinit=/etc/gdb/gdbinit --enable-targets=all make -j7

**Comment by disconnect3d** [comment]
I believe you may need >= 3.6, but I don't remember exactly :(.

**Comment by D1ag0n-Young** [comment]
Just used “../configure --disable-nls --disable-werror --with-system-readline --with-python=/usr/bin/python3.5 --with-system-gdbinit=/etc/gdb/gdbinit --enable-targets=all”
After compiling it, the following error appears:



libtool: link: ranlib .libs/libopcodes.a
libtool: link: ( cd ".libs" &amp;&amp; rm -f "libopcodes.la" &amp;&amp; ln -s "../libopcodes.la" "libopcodes.la" )
libtooldir=`/bin/bash ./libtool --config | sed -n -e 's/^objdir=//p'`; \
if [ -f $libtooldir/libopcodes.a ]; then \
&nbsp; cp $libtooldir/libopcodes.a libopcodes.tmp; \
&nbsp; ranlib libopcodes.tmp; \
&nbsp; /bin/bash ../../opcodes/../move-if-change libopcodes.tmp libopcodes.a; \
else true; fi
touch stamp-lib
make[4]: Leaving directory '/root/gdb-10.2/build/opcodes'
Making all in po
make[4]: Entering directory '/root/gdb-10.2/build/opcodes/po'
make[4]: Nothing to be done for 'all'.
make[4]: Leaving directory '/root/gdb-10.2/build/opcodes/po'
make[3]: Leaving directory '/root/gdb-10.2/build/opcodes'
make[2]: Leaving directory '/root/gdb-10.2/build/opcodes'
make[1]: Leaving directory '/root/gdb-10.2/build'
Makefile:853: recipe for target 'all' failed
make: *** [all] Error 2









------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年5月13日(星期四) 晚上8:42
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [pwndbg/pwndbg] An error occurred with the pwngdb plug-in for gdb10.2 (#920)






我相信你可能需要&gt;=3.6，但我不记得具体是：（。

—
您正在接收此消息，因为您编写了线程。
直接回复此邮件，在GitHub上查看或者取消订阅.

**Comment by disconnect3d** [comment]
Is that the full error trace/log? It seems we are missing something here. It may be that you are missing some dependencies required to build GDB and some errors above what you shown are probably showing this (sadly, they do not error early on...).

Also, I would recommend against building things _under root user_ and only using `sudo <command>` when needed (e.g. for `make install`).

**Comment by D1ag0n-Young** [comment]
```
Gǎnxiè, zuìhòu zhǐ shǐyòng cānshù ‘--with-python=/usr/bin/python3.5’ Biānyì chénggōng, shǐyòng zhèngcháng. Wǒ hái xiǎng wèn yīgè wèntí:Gdb-multiarch de gdb bǎnběn zěnme shēngjí? Tā de gdb bǎnběn hé biānyì de gdb bǎnběn bìng bùyīzhì ➜ ~$ gdb-multiarch -v GNU gdb (Ubuntu 7.11.1-0Ubuntu1~16.5) 7.11.1 Copyright (C) 2016 Free Software Foundation, Inc. License GPLv3+: GNU GPL version 3 or later <http://Gnu.Org/licenses/gpl.Html&gt; This is free software: You are free to change and redistribute it. There is NO WARRANTY, to the extent permitted by law. Type"show copying" and"show warranty" for details. This GDB was configured as"x86_64-linux-gnu". Type"show configuration" for configuration details. For bug reporting instructions, please see: <Http://Www.Gnu.Org/software/gdb/bugs/&gt;. Find the GDB manual and other documentation resources online at: <Http://Www.Gnu.Org/software/gdb/documentation/&gt;. For help, type"help". Type"apropos word" to search for commands related to"word". ➜ ~$ Gdb -v GNU gdb (GDB) 10.2 Copyright (C) 2021 Free Software Foundation, Inc. License GPLv3+: GNU GPL version 3 or later <http://Gnu.Org/licenses/gpl.Html&gt; This is free software: You are free to change and redistribute it. There is NO WARRANTY, to the extent permitted by law. Ubuntu bǎnběn:16.04 Wǒ yòng de “apt-get install gdb-multiarch” qù ānzhuāng de
展开
```

Thanks, in the end, only use the parameter ‘--with-python=/usr/bin/python3.5’ to compile successfully and use it normally. I also want to ask a question: How to upgrade the gdb version of gdb-multiarch? His gdb version is not consistent with the compiled gdb version 
```
➜ ~$ gdb-multiarch -v GNU gdb (Ubuntu 7.11.1-0ubuntu1~16.5) 7.11.1 Copyright (C) 2016 Free Software Foundation, Inc. License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html&gt; This is free software: you are free to change and redistribute it. There is NO WARRANTY, to the extent permitted by law. Type "show copying" and "show warranty" for details. This GDB was configured as "x86_64-linux-gnu". Type "show configuration" for configuration details. For bug reporting instructions, please see: <http://www.gnu.org/software/gdb/bugs/&gt;. Find the GDB manual and other documentation resources online at: <http://www.gnu.org/software/gdb/documentation/&gt;. For help, type "help". Type "apropos word" to search for commands related to "word". 
```

```
➜ ~$ gdb -v
GNU gdb (GDB) 10.2 Copyright (C) 2021 Free Software Foundation, Inc. License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html&gt; This is free software: you are free to change and redistribute it. There is NO WARRANTY, to the extent permitted by law.
```
ubuntu version: 16.04 I used "apt-get install gdb-multiarch" to install 



_EDIT by disconnect3d: I tried to make this message more readable._

**Comment by D1ag0n-Young** [comment]
Thank you, it is indeed a problem with the python version, python3 should be used

**Comment by 1094093288** [comment]
Hello, I want to ask a question. I want to use gdb to debug mips architecture programs,&nbsp; After using the pwndbg plug-in, shows the following exceptions:


➜ ~/Desktop/pwn-test/mips-pwn$ gdb-pwngdb stack_bof_2 -q
Reading symbols from stack_bof_2...
(No debugging symbols found in stack_bof_2)
pwndbg: loaded 196 commands. Type pwndbg [filter] for a list.
pwndbg: created $rebase, $ida gdb functions (can be used with print/break)
pwndbg&gt; target remote:12345
Remote debugging using :12345
warning: remote target does not support file transfer, attempting to access files from local filesystem.
Reading symbols from /root/Desktop/pwn-test/mips-pwn/lib/ld-2.23.so...
(No debugging symbols found in /root/Desktop/pwn-test/mips-pwn/lib/ld-2.23.so)
0x767cad00 in ?? () from /root/Desktop/pwn-test/mips-pwn/lib/ld-2.23.so
warning: .dynamic section for "/etc/qemu-binfmt/mipsel/lib/ld.so.1" is not at the expected address (wrong library or version mismatch?)
Exception occurred: context: Invalid option (CS_ERR_OPTION) (<class 'capstone.CsError'&gt;)
For more info invoke `set exception-verbose on` and rerun the command
or debug it by yourself with `set exception-debugger on`
pwndbg&gt; ni
warning: GDB can't find the start of the function at 0x767cad04.


&nbsp; &nbsp; GDB is unable to find the start of the function at 0x767cad04
and thus can't determine the size of that function's stack frame.
This means that GDB may be unable to access that stack frame, or
the frames below it.
&nbsp; &nbsp; This problem is most likely caused by an invalid program counter or
stack pointer.
&nbsp; &nbsp; However, if you think GDB should simply search farther back
from 0x767cad04 for code which looks like the beginning of a
function, you can increase the range of the search using the `set
heuristic-fence-post' command.
warning: GDB can't find the start of the function at 0x767cad04.
0x767cad04 in ?? () from /etc/qemu-binfmt/mipsel/lib/ld.so.1
warning: GDB can't find the start of the function at 0x767cad04.
Exception occurred: context: Invalid option (CS_ERR_OPTION) (<class 'capstone.CsError'&gt;)
For more info invoke `set exception-verbose on` and rerun the command
or debug it by yourself with `set exception-debugger on`




This makes it impossible to view specific registers. What is the reason for this?




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年5月13日(星期四) 晚上8:58
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [pwndbg/pwndbg] An error occurred with the pwngdb plug-in for gdb10.2 (#920)





 
Is that the full error trace/log? It seems we are missing something here. It may be that you are missing some dependencies required to build GDB and some errors above what you shown are probably showing this (sadly, they do not error early on...).
 
Also, I would recommend against building things under root user and only using sudo <command&gt; when needed (e.g. for make install).
