### ISSUE TITLE
add-symbol-file should not specify a base address

### ISSUE THREAD

**Issue by ConnorNelson** [pwndbg/pwndbg#978]
This happens when connecting to a remote target:
```
hacker@babyrop_level10:~$ gdb -ex 'target remote :1234'
...
add-symbol-file /tmp/tmp_yea7f3g/babyrop_level10.0 0x555555554000
...
pwndbg> b main
Breakpoint 1 at 0x555555555581 (2 locations)
pwndbg> info b
Num     Type           Disp Enb Address            What
1       breakpoint     keep y   <MULTIPLE>         
1.1                         y   0x0000555555555581 <main>
1.2                         y   0x00005555555567c1 
```
This double breakpoint results in `\xcc` bytes incorrectly polluting memory, and I've seen this corrupt the GOT and crash my program as a result.

https://github.com/pwndbg/pwndbg/blob/05036defa01d4d47bfad56867f53470a29fcdc89/pwndbg/symbol.py#L261

Why is the base address being specified here? According to the help info for `add-symbol-file`, if anything is specified for `[ADDR]`, it should be the location of the `.text` section.

```
(gdb) help add-symbol-file
Load symbols from FILE, assuming FILE has been dynamically loaded.
Usage: add-symbol-file FILE [-readnow | -readnever] [-o OFF] [ADDR] [-s SECT-NAME SECT-ADDR]...
ADDR is the starting address of the file's text.
Each '-s' argument provides a section name and address, and
should be specified if the data and bss segments are not contiguous
with the text.  SECT-NAME is a section name to be loaded at SECT-ADDR.
OFF is an optional offset which is added to the default load addresses
of all sections for which no other address was specified.
The '-readnow' option will cause GDB to read the entire symbol file
immediately.  This makes the command slower, but may make future operations
faster.
The '-readnever' option will prevent GDB from reading the symbol file's
symbolic debug information.
```

If we just omit the address, `gdb` will automatically find the `.text` section and use that address. Things would probably fail if there isn't a `.text` section defined, but I'm not really sure what the correct solution would be in this case anyways.

**Comment by ConnorNelson** [comment]
I just realized that this is the same issue as https://github.com/pwndbg/pwndbg/issues/177.

I'm not really understanding why this issue has not yet been resolved? The current behavior is incorrect. Omitting the address fixes the problem.

**Comment by disconnect3d** [comment]
> I'm not really understanding why this issue has not yet been resolved? The current behavior is incorrect. Omitting the address fixes the problem.

Because nobody send a PR for that matter! Heh ;)

Some things to consider (or just nice to have things):
1. Is the `add-symbol-file` feature in Pwndbg needed at all? It is invoked automatically via `autofech` function in pwndbg/symbol.py, but when I looked at it recently it seemed to me that things work fine without it. What are the cases when it is indeed required? (Maybe it was added for some old GDB that didn't do this automatically?)
2. Can we somehow simulate the case when `.text` is not there?
3. If we need to fetch some ELF/section/functions metadata out of a binary, we could pull of pwntools for it. I am going to do it anyway at some point in order to add commands like patching instructions (via their `asm` functionality).
4. Can we maybe add a testcase for this buggy behavior?

**Comment by Codadillo** [comment]
As far as 1 goes, I have had a scenario where `add-symbol-file` was useful. It was a while ago so I don't have the exact files that I needed it for, but I ran into some issues where debugging symbol files weren't getting correctly added at the right base. I think I also had an application where I wanted to switch between symbol files. 
Both of these might be too niche/something for which I might have not needed `add-symbol-file`, but it did solve my issues.
