### ISSUE TITLE
vmmap doesn't work on qemu-arm

### ISSUE THREAD

**Issue by killthatshaman** [pwndbg/pwndbg#981]
### Description
When using Qemu-Arm and Gdb-multiarch on Ubuntu20.04 to remotely debug the arm-architecture program, the display of vmmap is abnormal, and it can be displayed normally after the version is rolled back to `1.1.0 build: 9250cc5`.

```
pwndbg> vmmap
LEGEND: STACK | HEAP | CODE | DATA | RWX | RODATA
       0x0 0xffffffff rwxp ffffffff 0      [qemu]

[QEMU target detected - vmmap result might not be accurate; see `help vmmap`]
```

### Steps to reproduce
```bash
qemu-arm -g 1234 -L /usr/arm-linux-gnueabihf/ ./a.out
```
Then open gdb-multiarch and use `target remote: 1234`

### My setup
OS:Ubuntu20.04 x86_64
Qemu-version : 1:4.2-3ubuntu6.18
```
pwndbg> version
Gdb:      9.2
Python:   3.8.10 (default, Sep 28 2021, 16:10:42)  [GCC 9.3.0]
Pwndbg:   1.1.0 build: 5c0627d
Capstone: 4.0.1024
Unicorn:  1.0.2
```

**Comment by disconnect3d** [comment]
Hey, the main issue here is that QEMU does not provide us enough information to fetch this information normally. I have finally spend some time on that and sent a patch to QEMU to make this happen: https://lists.gnu.org/archive/html/qemu-devel/2022-02/msg04418.html

Ofc this could be worked around by us by e.g. inspecting the qemu process memory maps and filtering them to display the inferior maps (similarly to what qemu does when the inferior wants to read its /proc/self/maps file). However, I prefer a "proper" solution here and so that's why I went with fixing this on the qemu side.

Hopefully the patch will be merged at some time and we can support this properly from the next QEMU release.

**Comment by disconnect3d** [comment]
Fwiw vmmap works on latest GDB + QEMU:
![image](https://github.com/pwndbg/pwndbg/assets/10009354/da5bf5c7-aac0-4651-8ed5-2521f3501e84)

QEMU folks took the patch I was developing and took it further and the info proc features got added into QEMU 8.1:
![image](https://github.com/pwndbg/pwndbg/assets/10009354/59dcdbe7-2596-4f78-a470-2500bd221846)

**Comment by disconnect3d** [comment]
Okay, the above shows aarch64, but I believe things should also work for ARM too.
