### ISSUE TITLE
maximum recursion depth exceeded - gdb -c core_dump

### ISSUE THREAD

**Issue by securitylab-repository** [pwndbg/pwndbg#985]
[core.4408.zip](https://github.com/pwndbg/pwndbg/files/7609626/core.4408.zip)
### Description

We have this error when we analyse a core dump generated after segmentation fault due to the buffer overflow : 
Exception occurred: Error: maximum recursion depth exceeded while calling a Python object (<class 'RecursionError'>).
We launch gdb and thus pwndbg with this option : -c 

### My setup

ubuntu bionic64 on vagrant and virtualbox
python version : any
gdb version : 8.1.1-0ubuntu1

>

**Comment by disconnect3d** [comment]
Can you provide a minimal working example of this so I can fix it once and for all?

**Comment by securitylab-repository** [comment]
this is the core dump 
[core.4408.zip](https://github.com/pwndbg/pwndbg/files/7609641/core.4408.zip)

**Comment by disconnect3d** [comment]
Thanks, I can reproduce this and I get some workaround which isn't perfect yet but it can be found here in case u want to use it now: https://github.com/disconnect3d/pwndbg/tree/workaround-985

Due how it is made Pwndbg does not resolve proper vmmap, so e.g. legend does not work well. I guess we could maybe parse `info proc mapping` instead of all the thing we do now or we did in the past to grab those pages in this particular case...

**Comment by securitylab-repository** [comment]
Yes, it works better now.

Thanks.

Le ven. 26 nov. 2021 à 19:37, Disconnect3d ***@***.***> a
écrit :

**Comment by disconnect3d** [comment]
Related: https://sourceware.org/bugzilla/show_bug.cgi?id=29508

**Comment by disconnect3d** [comment]
This has been fixed in #1079 

The returned vmmap information is not ideal, but that's more or less what we get right away from GDB.

(We may be able to improve this by using readelf on the core file, but it would not be so generic solution/may not work in all cases etc. so I am still not sure about using it)

<img width="858" alt="image" src="https://user-images.githubusercontent.com/10009354/185766633-b03b2095-ed7c-48b1-91ef-69be5aac854b.png">
